import test from 'node:test'; import assert from 'node:assert/strict';
import { registry } from '../src/registry.js'; import { reconcileRegistry, reconcileSpecialistInventory } from '../src/registry-reconciliation.js'; import { DiscoveredSpecialist, SpecialistInventoryProvider } from '../src/specialist-inventory.js';

const approved={alpha:{specialistId:'alpha',displayName:'Alpha',chatgptUrl:'https://example.test/alpha',canValidateCodex:true,runtime:{status:'ACTIVE' as const,type:'openai_agent' as const,runtimeId:'alpha-runtime',version:'1',instructionRef:'alpha',outputSchema:'alpha',timeoutSeconds:1,maxAttempts:1},inventoryIdentity:'alpha-key'}, beta:{specialistId:'beta',displayName:'Beta',canValidateCodex:false}};
const available=(specialists:readonly DiscoveredSpecialist[])=>({status:'AVAILABLE' as const,source:'test',observedAt:'2026-01-01T00:00:00.000Z',specialists});
const one=(r:ReturnType<typeof reconcileRegistry>,status:string)=>r.outcomes.find(x=>x.status===status)!;

test('LV-0A-01 matching inventory has no false changes',()=>{const r=reconcileRegistry(approved,available([{specialistId:'alpha',displayName:'Alpha',chatgptUrl:'https://example.test/alpha'},{specialistId:'beta',displayName:'Beta'}]));assert.equal(r.freshness,'VERIFIED');assert.deepEqual(r.outcomes.map(x=>x.status),['MATCHED','MATCHED']);assert.equal(r.approvedRegistryChanged,false);});
test('LV-0A-02 new discovery is unreviewed and non-routable',()=>{const r=reconcileRegistry(approved,available([{specialistId:'new',displayName:'New'}]));const o=one(r,'NEW_UNREVIEWED');assert.equal(o.routable,false);assert.equal(o.runtime,'UNVERIFIED');assert.equal(o.reviewRequired,true);assert.deepEqual(approved,approved);});
test('LV-0A-03 discovery does not approve a specialist',()=>{const r=reconcileRegistry({},available([{specialistId:'new',displayName:'New'}]));assert.equal(one(r,'NEW_UNREVIEWED').ownership,'UNASSIGNED');assert.equal(one(r,'NEW_UNREVIEWED').routable,false);});
test('LV-0A-04 missing discovery does not delete approval',()=>{const r=reconcileRegistry(approved,available([]));assert.equal(one(r,'MISSING_FROM_INVENTORY').specialistId,'alpha');assert.ok(r.approvedRegistrySnapshot.alpha);});
test('LV-0A-05 weak identity change is a possible rename only',()=>{const r=reconcileRegistry(approved,available([{specialistId:'renamed',displayName:'Alpha Updated',chatgptUrl:'https://example.test/alpha'}]));const o=one(r,'POSSIBLE_RENAME');assert.equal(o.approvedSpecialistId,'alpha');assert.equal(o.routable,false);});
test('LV-0A-06 unavailable provider is unverified and preserves registry',async()=>{const provider: SpecialistInventoryProvider={discover:async()=>({status:'UNAVAILABLE',source:'test',observedAt:'2026-01-01T00:00:00.000Z',reason:'offline'})};const r=await reconcileSpecialistInventory(provider,approved);assert.equal(r.freshness,'UNVERIFIED');assert.equal(one(r,'PROVIDER_UNAVAILABLE').status,'PROVIDER_UNAVAILABLE');assert.ok(r.approvedRegistrySnapshot.alpha);});
test('LV-0A-07 navigation metadata cannot establish runtime truth',()=>{const r=reconcileRegistry({},available([{specialistId:'new',displayName:'New',chatgptUrl:'https://example.test/new',description:'runs code',navigationMetadata:{href:'/gpt/new'}}]));const o=one(r,'NEW_UNREVIEWED');assert.equal(o.runtime,'UNVERIFIED');assert.equal(o.capabilities,'UNVERIFIED');});
test('LV-0A-08 reconciliation is non-mutating',()=>{const before=JSON.stringify(approved);const r=reconcileRegistry(approved,available([{specialistId:'new',displayName:'New'}]));assert.equal(JSON.stringify(approved),before);assert.equal(r.approvedRegistryChanged,false);assert.deepEqual(Object.keys(approved),['alpha','beta']);});

test('provider exceptions become explicit unavailability',async()=>{const provider: SpecialistInventoryProvider={discover:async()=>{throw new Error('boom');}};const r=await reconcileSpecialistInventory(provider,registry);assert.equal(r.freshness,'UNVERIFIED');assert.equal(r.outcomes[0].status,'PROVIDER_UNAVAILABLE');});
