// @ts-nocheck
import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { PgStore } from '../src/pg-store.js';

const url = process.env.PG_TEST_URL;
const makeStore = () => new PgStore(url);
const id = () => randomUUID();
const input = (requestId = id()) => ({requestId,workflowType:'software' as const,logicalSpecialistId:'architecture-security-advisor',runtimeId:'runtime',validationRequired:true,effectiveClassification:'PUBLIC' as const,objective:'task22c',context:{},requiresImplementation:true});
const decision = (workflowId, overrides = {}) => ({id:id(),workflowId,selectedSpecialistId:'architecture-security-advisor',routingConfidence:'CLEAR' as const,routingReason:'matched ownership',decisionType:'INITIAL' as const,supersedesDecisionId:null,createdAt:new Date().toISOString(),...overrides});
const candidate = (routingDecisionId, rank, specialistId = `specialist-${rank}`) => ({id:id(),routingDecisionId,specialistId,rank,matchReason:`candidate ${rank}`});
const setup = async () => { const store=makeStore(); const workflow=await store.createWorkflow(input(),'task22c','create'); return {store,workflow}; };

test('Task 22C persists and retrieves a decision with deterministic candidates', {skip:!url}, async()=>{const {store,workflow}=await setup();try{const d=decision(workflow.id);const cs=[candidate(d.id,2),candidate(d.id,1)];await store.recordRoutingDecisionWithCandidates(d,cs);assert.deepEqual(await store.getRoutingDecision(d.id),d);assert.deepEqual((await store.getRoutingCandidates(d.id)).map(x=>x.rank),[1,2]);assert.deepEqual((await store.getRoutingHistory(workflow.id)).map(x=>x.id),[d.id]);}finally{await store.pool.end();}});

test('Task 22C decision and candidates are atomic and retryable', {skip:!url}, async()=>{const {store,workflow}=await setup();try{const d=decision(workflow.id);await assert.rejects(()=>store.recordRoutingDecisionWithCandidates(d,[candidate(id(),1)]),/ROUTING_CANDIDATE_DECISION_MISMATCH/);assert.equal(await store.getRoutingDecision(d.id),undefined);assert.deepEqual(await store.getRoutingHistory(workflow.id),[]);const cs=[candidate(d.id,1)];await store.recordRoutingDecisionWithCandidates(d,cs);assert.equal((await store.getRoutingCandidates(d.id)).length,1);}finally{await store.pool.end();}});

test('Task 22C preserves superseded history and resolves the latest decision', {skip:!url}, async()=>{const {store,workflow}=await setup();try{const a=decision(workflow.id,{createdAt:'2026-09-11T00:00:00.000Z'});const b=decision(workflow.id,{decisionType:'USER_OVERRIDE',routingReason:'explicit user choice',supersedesDecisionId:a.id,createdAt:'2026-09-11T00:00:01.000Z'});await store.recordRoutingDecisionWithCandidates(a,[candidate(a.id,1)]);await store.recordRoutingDecisionWithCandidates(b,[candidate(b.id,1,'override-specialist')]);assert.equal((await store.getRoutingDecision(a.id)).routingReason,'matched ownership');assert.equal((await store.getLatestRoutingDecision(workflow.id)).id,b.id);assert.deepEqual((await store.getRoutingHistory(workflow.id)).map(x=>x.id),[a.id,b.id]);}finally{await store.pool.end();}});

test('Task 22C survives a new PgStore instance and retains NO_MATCH and competing PROBABLE candidates', {skip:!url}, async()=>{const first=makeStore();const workflow=await first.createWorkflow(input(),'task22c','restart');const noMatch=decision(workflow.id,{selectedSpecialistId:null,routingConfidence:'NO_MATCH',routingReason:'no registered owner',decisionType:'FALLBACK',createdAt:'2026-09-11T00:00:01.000Z'});const probable=decision(workflow.id,{routingConfidence:'PROBABLE',routingReason:'probable ownership',decisionType:'DOWNSTREAM_ROUTE',createdAt:'2026-09-11T00:00:02.000Z'});await first.recordRoutingDecisionWithCandidates(noMatch,[]);await first.recordRoutingDecisionWithCandidates(probable,[candidate(probable.id,2),candidate(probable.id,1,'competing-specialist')]);await first.pool.end();const second=makeStore();try{const history=await second.getRoutingHistory(workflow.id);assert.equal(history.length,2);assert.equal(history[0].routingConfidence,'NO_MATCH');assert.equal(history[0].selectedSpecialistId,null);assert.equal((await second.getRoutingCandidates(probable.id))[0].specialistId,'competing-specialist');assert.equal((await second.getLatestRoutingDecision(workflow.id)).id,probable.id);}finally{await second.pool.end();}});

test('Task 22C enforces foreign keys, values, ranks, and candidate uniqueness', {skip:!url}, async()=>{const {store,workflow}=await setup();try{const d=decision(workflow.id);await store.recordRoutingDecision(d);await assert.rejects(()=>store.pool.query('INSERT INTO routing_candidates(id,routing_decision_id,specialist_id,rank,match_reason) VALUES($1,$2,$3,$4,$5)',[id(),id(),'x',1,'bad parent']),/routing_candidates/);await assert.rejects(()=>store.pool.query('INSERT INTO routing_decisions(id,workflow_id,routing_confidence,routing_reason,decision_type,created_at) VALUES($1,$2,$3,$4,$5,now())',[id(),workflow.id,'INVALID','bad','INITIAL']),/routing_decisions/);await assert.rejects(()=>store.pool.query('INSERT INTO routing_candidates(id,routing_decision_id,specialist_id,rank,match_reason) VALUES($1,$2,$3,$4,$5)',[id(),d.id,'x',0,'bad rank']),/routing_candidates/);await store.recordRoutingCandidates([candidate(d.id,1,'x')]);await assert.rejects(()=>store.recordRoutingCandidates([candidate(d.id,1,'y')]),/routing_candidates/);}finally{await store.pool.end();}});
test('Task 22C rejects invalid decision type, missing workflow, missing supersession, and duplicate candidate specialist', {skip:!url}, async()=>{const {store,workflow}=await setup();try{await assert.rejects(()=>store.pool.query('INSERT INTO routing_decisions(id,workflow_id,routing_confidence,routing_reason,decision_type,created_at) VALUES($1,$2,$3,$4,$5,now())',[id(),workflow.id,'CLEAR','bad','INVALID']),/routing_decisions/);await assert.rejects(()=>store.recordRoutingDecision(decision(id())),/routing_decisions/);await assert.rejects(()=>store.recordRoutingDecision(decision(workflow.id,{supersedesDecisionId:id()})),/SUPERSEDED_ROUTING_DECISION_NOT_FOUND/);const d=decision(workflow.id);await store.recordRoutingDecisionWithCandidates(d,[candidate(d.id,1,'same-specialist')]);await assert.rejects(()=>store.recordRoutingCandidates([candidate(d.id,2,'same-specialist')]),/routing_candidates/);}finally{await store.pool.end();}});

test('Task 22C rejects cross-workflow supersession at the persistence boundary', {skip:!url}, async()=>{const a=await setup();const b=await setup();try{const prior=decision(a.workflow.id);await a.store.recordRoutingDecision(prior);const next=decision(b.workflow.id,{supersedesDecisionId:prior.id});await assert.rejects(()=>b.store.recordRoutingDecision(next),/SUPERSEDED_ROUTING_WORKFLOW_MISMATCH/);assert.equal(await b.store.getRoutingDecision(next.id),undefined);}finally{await a.store.pool.end();await b.store.pool.end();}});

test('Task 22C concurrent history writes create distinct durable decisions', {skip:!url}, async()=>{const {store,workflow}=await setup();try{const decisions=Array.from({length:3},(_,n)=>decision(workflow.id,{routingReason:`concurrent ${n}`,createdAt:`2026-09-11T00:00:0${n}.000Z`}));await Promise.all(decisions.map(d=>store.recordRoutingDecision(d)));const history=await store.getRoutingHistory(workflow.id);assert.deepEqual(history.map(x=>x.id),decisions.map(x=>x.id));}finally{await store.pool.end();}});
