// @ts-nocheck
import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {PgStore} from '../src/pg-store.js';
import {registry} from '../src/registry.js';

const url=process.env.PG_TEST_URL; const id=()=>randomUUID();
const input=(requestId=id())=>({requestId,workflowType:'non_code',logicalSpecialistId:'previous-specialist',runtimeId:'previous-runtime',validationRequired:false,effectiveClassification:'PUBLIC',objective:'override test',context:{},requiresImplementation:false});
const initial=(workflowId, confidence='CLEAR', selected='previous-specialist')=>({id:id(),workflowId,selectedSpecialistId:selected,routingConfidence:confidence,routingReason:'original route',decisionType:'INITIAL',supersedesDecisionId:null,createdAt:new Date().toISOString()});

async function setup(){const store=new PgStore(url);const workflow=await store.createWorkflow(input(),'22h','create');const decision=initial(workflow.id);await store.recordRoutingDecisionWithCandidates(decision,[{id:id(),routingDecisionId:decision.id,specialistId:'previous-specialist',rank:1,matchReason:'original evidence'}]);return {store,workflow,decision};}

test('Task 22H persists USER_OVERRIDE, supersedes history, updates projection, and survives restart',{skip:!url},async()=>{const {store,workflow,decision}=await setup();const before=JSON.stringify(registry);try{const result=await store.applyUserOverride(workflow.id,'architecture-security-advisor','please use the architecture specialist','operator',decision.id);assert.equal(result.decision.decisionType,'USER_OVERRIDE');assert.equal(result.decision.selectedSpecialistId,'architecture-security-advisor');assert.equal(result.decision.supersedesDecisionId,decision.id);assert.equal(result.decision.routingConfidence,'PROBABLE');assert.equal((await store.getRoutingDecision(decision.id)).routingReason,'original route');assert.equal((await store.getLatestRoutingDecision(workflow.id)).id,result.decision.id);assert.equal((await store.getWorkflow(workflow.id)).logicalSpecialistId,'architecture-security-advisor');assert.equal((await store.getRoutingCandidates(result.decision.id))[0].matchReason,'original evidence');assert.equal(JSON.stringify(registry),before);await store.pool.end();const fresh=new PgStore(url);try{const history=await fresh.getRoutingHistory(workflow.id);assert.deepEqual(history.map(x=>x.decisionType),['INITIAL','USER_OVERRIDE']);assert.equal((await fresh.getLatestRoutingDecision(workflow.id)).selectedSpecialistId,'architecture-security-advisor');assert.equal((await fresh.getEvents(workflow.id)).some(x=>x.eventType==='ROUTING_OVERRIDDEN'),true);}finally{await fresh.pool.end();}}catch(e){await store.pool.end();throw e;}});

test('Task 22H validates targets, stale writes, same-specialist no-op, and atomic rollback',{skip:!url},async()=>{const {store,workflow,decision}=await setup();try{await assert.rejects(()=>store.applyUserOverride(workflow.id,'missing-specialist'),/INVALID_OVERRIDE_TARGET/);await assert.rejects(()=>store.applyUserOverride(workflow.id,'architecture-security-advisor','', 'operator',id()),/STALE_ROUTING_DECISION/);const first=await store.applyUserOverride(workflow.id,'architecture-security-advisor','first');const again=await store.applyUserOverride(workflow.id,'architecture-security-advisor','repeat');assert.equal(again.decision.id,first.decision.id);assert.equal((await store.getRoutingHistory(workflow.id)).length,2);const other=await store.createWorkflow(input(),'22h','rollback');const d=initial(other.id);await store.recordRoutingDecision(d);const original=store.event;store.event=async()=>{throw new Error('TASK22H_OVERRIDE_AUDIT_FAIL')};await assert.rejects(()=>store.applyUserOverride(other.id,'architecture-security-advisor'),/TASK22H_OVERRIDE_AUDIT_FAIL/);store.event=original;assert.equal((await store.getRoutingHistory(other.id)).length,1);assert.equal((await store.getWorkflow(other.id)).logicalSpecialistId,'previous-specialist');}finally{await store.pool.end();}});

test('Task 22H supports NO_MATCH and preserves an ambiguous clarification as superseded history',{skip:!url},async()=>{const store=new PgStore(url);try{const noMatch=await store.createWorkflow(input(),'22h','nomatch');const none=initial(noMatch.id,'NO_MATCH',null);none.routingReason='no registered owner';await store.recordRoutingDecision(none);const redirected=await store.applyUserOverride(noMatch.id,'architecture-security-advisor');assert.equal(redirected.decision.decisionType,'USER_OVERRIDE');assert.equal((await store.getLatestRoutingDecision(noMatch.id)).id,redirected.decision.id);const ambiguous=await store.createWorkflow(input(),'22h','ambiguous');const a=initial(ambiguous.id,'AMBIGUOUS',null);await store.recordRoutingDecisionWithCandidates(a,[{id:id(),routingDecisionId:a.id,specialistId:'possible',rank:1,matchReason:'possible'}]);const clarification=await store.createPendingClarification({workflowId:ambiguous.id,routingDecisionId:a.id,question:'Which specialist should handle this?'});const over=await store.applyUserOverride(ambiguous.id,'architecture-security-advisor');assert.equal(over.workflow.status,'ROUTED');assert.equal((await store.getClarification(clarification.id)).status,'SUPERSEDED');assert.equal(await store.getPendingClarification(ambiguous.id),undefined);assert.equal((await store.getRoutingDecision(a.id)).routingConfidence,'AMBIGUOUS');}finally{await store.pool.end();}});

test('Task 22H serializes concurrent overrides with expected-current protection',{skip:!url},async()=>{const {store,workflow,decision}=await setup();try{const results=await Promise.allSettled([store.applyUserOverride(workflow.id,'architecture-security-advisor','a','operator',decision.id),store.applyUserOverride(workflow.id,'github-oracle','b','operator',decision.id)]);assert.equal(results.filter(x=>x.status==='fulfilled').length,1);assert.equal(results.filter(x=>x.status==='rejected').length,1);assert.match(results.find(x=>x.status==='rejected').reason.message,/STALE_ROUTING_DECISION/);assert.equal((await store.getRoutingHistory(workflow.id)).length,2);}finally{await store.pool.end();}});
