// @ts-nocheck
import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { spawn } from 'node:child_process';
import { PgStore } from '../src/pg-store.js';

const url=process.env.PG_TEST_URL;const id=()=>randomUUID();
test('Task 22E approval API retrieves and decides a durable approval', {skip:!url}, async()=>{const store=new PgStore(url);const workflow=await store.createWorkflow({requestId:id(),workflowType:'software',logicalSpecialistId:'architecture-security-advisor',runtimeId:'runtime',validationRequired:true,effectiveClassification:'PUBLIC',objective:'approval api',context:{principal:{id:'approver',roles:[],scopes:[],authType:'token'}},requiresImplementation:true},'task22e-api','create');const approval=await store.createPendingApproval({workflowId:workflow.id,protectedActionId:'protected-stage',scopeFingerprint:'scope-v1',reason:'cost changes',categories:['COST']});await store.pool.end();const port=18102;const child=spawn(process.execPath,['dist/src/server.js'],{env:{...process.env,APP_MODE:'deployed',AUTH_MODE:'token',DATABASE_URL:url,PGPASSWORD:process.env.PGPASSWORD,ORCHESTRATOR_API_TOKEN:'test-only-token',AUTH_PRINCIPALS:JSON.stringify({'test-only-token':{id:'approver',roles:[],scopes:[]}}),PORT:String(port)},stdio:['ignore','pipe','pipe']});try{await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('SERVER_START_TIMEOUT')),5000);child.stdout.on('data',chunk=>{if(String(chunk).includes('server_started')){clearTimeout(timer);resolve();}});child.on('error',reject);});const headers={authorization:'Bearer test-only-token'};const get=await fetch(`http://127.0.0.1:${port}/v1/workflows/${workflow.id}/approval`,{headers});assert.equal(get.status,200);assert.equal((await get.json()).id,approval.id);const post=await fetch(`http://127.0.0.1:${port}/v1/workflows/${workflow.id}/approval`,{method:'POST',headers:{...headers,'content-type':'application/json'},body:JSON.stringify({approvalId:approval.id,decision:'APPROVED',reason:'approved by operator'})});assert.equal(post.status,200);assert.equal((await post.json()).status,'APPROVED');}finally{child.kill('SIGTERM');}});
