// @ts-nocheck
import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { PgStore } from '../src/pg-store.js';
import { persistResolvedRouting, resolveRouting, routingDecision } from '../src/routing.js';

const url=process.env.PG_TEST_URL;const id=()=>randomUUID();
const input=()=>({requestId:id(),workflowType:'non_code',logicalSpecialistId:'architecture-security-advisor',runtimeId:'runtime',validationRequired:false,effectiveClassification:'PUBLIC',objective:'routing policy',context:{},requiresImplementation:false});
const rankById={owner:1,generic:2,a:1,b:2,python:1,architecture:2};
const c=(specialistId,ownership=[],specificity=0)=>{const canonical={owner:'architecture-security-advisor',generic:'policy-document-reviewer',a:'python-oracle',b:'github-oracle',python:'python-oracle',architecture:'architecture-security-advisor'}[specialistId]??specialistId;return {specialistId:canonical,rank:rankById[specialistId]??1,matchReason:'deterministic evidence',evidence:{specialistId:canonical,registryVersion:'1.0.0',ownershipMatches:ownership,capabilityMatches:[],workflowRelationship:'none',exclusionResult:'eligible',specificity,runtimeStatus:'MANUAL_ONLY',matchReason:'deterministic evidence'}};};
const candidateRows=(resolution,decisionId)=>resolution.candidates.map(x=>({id:id(),routingDecisionId:decisionId,specialistId:x.specialistId,rank:x.rank,matchReason:x.matchReason}));

test('Task 22G persists CLEAR, PROBABLE, and NO_MATCH without execution or clarification', {skip:!url}, async()=>{const s=new PgStore(url);try{for(const [candidates,confidence,selected] of [[[c('owner',['repo'],3),c('generic',[],1)],'CLEAR','architecture-security-advisor'],[[c('a',['python'],4),c('b',['architecture'],2)],'PROBABLE','python-oracle'],[[],'NO_MATCH',null]] as any){const w=await s.createWorkflow(input(),'22g','create');const resolution=resolveRouting(candidates);assert.equal(resolution.routingConfidence,confidence);assert.equal(resolution.selectedSpecialistId,selected);const result=await persistResolvedRouting(s,w.id,resolution);assert.equal((await s.getLatestRoutingDecision(w.id)).routingConfidence,confidence);assert.equal((await s.getLatestRoutingDecision(w.id)).selectedSpecialistId,selected);assert.equal(await s.getPendingClarification(w.id),undefined);assert.equal((await s.getAttempts(w.id)).length,0);assert.equal(result.candidates.length,candidates.length);}}finally{await s.pool.end();}});

test('Task 22G persists AMBIGUOUS routing and clarification atomically across restart', {skip:!url}, async()=>{const first=new PgStore(url);const w=await first.createWorkflow(input(),'22g','create');const resolution=resolveRouting([c('a',['repo'],2),c('b',['repo'],2)]);assert.equal(resolution.routingConfidence,'AMBIGUOUS');const result=await persistResolvedRouting(first,w.id,resolution);assert.equal(result.workflow.status,'AWAITING_CLARIFICATION');assert.equal(result.clarification.routingDecisionId,result.decision.id);await first.pool.end();const second=new PgStore(url);try{const d=await second.getRoutingDecision(result.decision.id);assert.equal(d.routingConfidence,'AMBIGUOUS');assert.equal(d.selectedSpecialistId,null);assert.equal((await second.getPendingClarification(w.id)).routingDecisionId,d.id);assert.equal((await second.getWorkflow(w.id)).status,'AWAITING_CLARIFICATION');assert.equal((await second.getRoutingCandidates(d.id)).length,2);assert.equal((await second.getAttempts(w.id)).length,0);}finally{await second.pool.end();}});

test('Task 22G ambiguous resolution rolls back decision, candidates, clarification, and state on failure', {skip:!url}, async()=>{const s=new PgStore(url);const w=await s.createWorkflow(input(),'22g','create');const original=s.event;s.event=async()=>{throw new Error('TASK22G_CLARIFICATION_FAIL');};try{const resolution=resolveRouting([c('a',['repo'],2),c('b',['repo'],2)]);await assert.rejects(()=>persistResolvedRouting(s,w.id,resolution),/TASK22G_CLARIFICATION_FAIL/);s.event=original;assert.equal((await s.getRoutingHistory(w.id)).length,0);assert.equal(await s.getPendingClarification(w.id),undefined);assert.equal((await s.getWorkflow(w.id)).status,'ROUTED');}finally{s.event=original;await s.pool.end();}});

test('Task 22G POST_CLARIFICATION reuses policy and preserves prior history', {skip:!url}, async()=>{const s=new PgStore(url);const w=await s.createWorkflow(input(),'22g','create');try{const initial=resolveRouting([c('a',['repo'],2),c('b',['repo'],2)]);const first=await persistResolvedRouting(s,w.id,initial);await s.recordClarificationResponse(first.clarification.id,'focus on Python implementation');const resumed=resolveRouting([c('python',['python'],4),c('architecture',['architecture'],1)]);const d=routingDecision(w.id,resumed,'POST_CLARIFICATION',first.decision.id);const result=await s.resumeClarification(w.id,first.clarification.id,d,candidateRows(resumed,d.id));assert.equal(result.decision.routingConfidence,'PROBABLE');assert.equal((await s.getRoutingDecision(first.decision.id)).routingConfidence,'AMBIGUOUS');assert.equal((await s.getLatestRoutingDecision(w.id)).id,d.id);assert.equal((await s.getRoutingCandidates(first.decision.id)).length,2);assert.equal((await s.getRoutingCandidates(d.id)).length,2);assert.equal((await s.getAttempts(w.id)).length,0);}finally{await s.pool.end();}});
