// @ts-nocheck
import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {spawn} from 'node:child_process';
import {PgStore} from '../src/pg-store.js';

const url=process.env.PG_TEST_URL; const id=()=>randomUUID();
const repository={repositoryId:'repo',source:'./repo',classification:'PUBLIC',allowedCallers:['operator'],allowedSpecialists:['architecture-security-advisor'],allowedExecutionTypes:['specialist'],allowedRefs:['main'],approvedRef:'main'};
test('Task 22H exposes a PostgreSQL-backed override endpoint',{skip:!url},async()=>{const store=new PgStore(url);const workflow=await store.createWorkflow({requestId:id(),workflowType:'non_code',logicalSpecialistId:'previous-specialist',runtimeId:'previous-runtime',validationRequired:false,effectiveClassification:'PUBLIC',objective:'override api',context:{principal:{id:'operator',roles:[],scopes:[],authType:'token'},resolvedRepository:repository},requiresImplementation:false},'22h-api','create');const decision={id:id(),workflowId:workflow.id,selectedSpecialistId:'previous-specialist',routingConfidence:'CLEAR',routingReason:'original',decisionType:'INITIAL',supersedesDecisionId:null,createdAt:new Date().toISOString()};await store.recordRoutingDecision(decision);await store.pool.end();const port=18103;const child=spawn(process.execPath,['dist/src/server.js'],{env:{...process.env,APP_MODE:'deployed',AUTH_MODE:'token',DATABASE_URL:url,ORCHESTRATOR_API_TOKEN:'test-only-token',AUTH_PRINCIPALS:JSON.stringify({'test-only-token':{id:'operator',roles:[],scopes:[]}}),ALLOWED_REPOSITORIES:JSON.stringify({repo:{...repository,repositoryId:undefined}}),PORT:String(port)},stdio:['ignore','pipe','pipe']});try{await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('SERVER_START_TIMEOUT')),5000);child.stdout.on('data',x=>{if(String(x).includes('server_started')){clearTimeout(timer);resolve(null);}});child.on('error',reject);});const headers={authorization:'Bearer test-only-token','content-type':'application/json'};const response=await fetch(`http://127.0.0.1:${port}/v1/workflows/${workflow.id}/override`,{method:'POST',headers,body:JSON.stringify({specialistId:'architecture-security-advisor',reason:'operator selection',expectedDecisionId:decision.id})});assert.equal(response.status,200);const body=await response.json();assert.equal(body.decision.decisionType,'USER_OVERRIDE');assert.equal(body.decision.selectedSpecialistId,'architecture-security-advisor');const invalid=await fetch(`http://127.0.0.1:${port}/v1/workflows/${workflow.id}/override`,{method:'POST',headers,body:JSON.stringify({specialistId:'unknown'})});assert.equal(invalid.status,400);}finally{child.kill('SIGTERM');}});
