// @ts-nocheck
import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { PgStore } from '../src/pg-store.js';
import { Orchestrator } from '../src/orchestrator.js';
import { registry } from '../src/registry.js';

const url=process.env.PG_TEST_URL;const id=()=>randomUUID();const store=()=>new PgStore(url);
const principal={id:'closure-worker',roles:['developer'],scopes:['run'],authType:'token',maxClassification:'PUBLIC'};
const repository={repositoryId:'closure-repo',source:'.',classification:'PUBLIC',allowedCallers:['closure-worker'],allowedSpecialists:['architecture-security-advisor'],allowedExecutionTypes:['specialist'],allowedRefs:['main'],approvedRef:'main'};
const input=(requestId=id())=>({requestId,workflowType:'non_code',logicalSpecialistId:'architecture-security-advisor',runtimeId:'architecture-security-advisor-api',validationRequired:false,effectiveClassification:'PUBLIC',objective:'approval closure',context:{principal,resolvedRepository:repository,specialistId:'architecture-security-advisor'},requiresImplementation:false});
const approval=(workflowId)=>({workflowId,protectedActionId:'specialist:architecture-security-advisor',scopeFingerprint:'scope-v1',reason:'material protected transition',categories:['EXECUTION_RISK']});

test('Task 22E closure: pending approval blocks claim and initiation effects', {skip:!url}, async()=>{const s=store();try{const w=await s.createWorkflow(input(),'closure','create');const a=await s.createPendingApproval(approval(w.id));assert.equal((await s.getWorkflow(w.id)).status,'AWAITING_APPROVAL');await assert.rejects(()=>s.claimStage(w.id,a.protectedActionId,'specialist','architecture-security-advisor-api','worker'),/APPROVAL_REQUIRED/);await assert.rejects(()=>s.recordInitiation(w.id,id(),{provider:'test'},'worker'),/ATTEMPT_NOT_OWNER/);assert.equal((await s.getAttempts(w.id)).length,0);assert.equal((await s.getApproval(a.id)).status,'PENDING');assert.equal((await s.getEvents(w.id)).some(e=>e.eventType==='INITIATION'),false);}finally{await s.pool.end();}});

test('Task 22E closure: pending approval blocks the normal external executor boundary', {skip:!url}, async()=>{const s=store();try{const w=await s.createWorkflow(input(),'closure','run');await s.createPendingApproval(approval(w.id));let calls=0;const o=new Orchestrator(s,{execute:async()=>{calls++;return {kind:'success',output:{objective:'x',requirements:[],constraints:[],affected_components:[],security_requirements:[],test_requirements:[],acceptance_criteria:[],validation_required:false,validation_reason:''},externalExecutionId:'external'}}} as any,{} as any,{} as any,{} as any);const context={principal,operation:'run',requestId:w.requestId,workflowId:w.id,specialistId:w.logicalSpecialistId,executionType:'specialist',effectiveClassification:'PUBLIC',resolvedRepository:repository,authorizationDecision:{allowed:true,ruleId:'test',decidedAt:new Date().toISOString()}};await assert.rejects(()=>o.run(w.id,context,'worker'),/APPROVAL_REQUIRED/);assert.equal(calls,0);assert.equal((await s.getAttempts(w.id)).length,0);assert.equal((await s.getEvents(w.id)).some(e=>e.eventType==='INITIATION'),false);}finally{await s.pool.end();}});

test('Task 22E closure: approved state survives restart and resumes through normal claim/initiation/execution', {skip:!url}, async()=>{const first=store();const w=await first.createWorkflow(input(),'closure','restart');const a=await first.createPendingApproval(approval(w.id));await first.decideApproval(a.id,'APPROVED','approved','closure-approver');assert.equal((await first.getAttempts(w.id)).length,0);await first.pool.end();const second=store();try{const persisted=await second.getApproval(a.id);assert.equal(persisted.status,'APPROVED');assert.equal(persisted.protectedActionId,a.protectedActionId);assert.equal(persisted.scopeFingerprint,'scope-v1');assert.equal((await second.getAttempts(w.id)).length,0);const original=registry['architecture-security-advisor'];const oldRuntimeStatus=original.runtimeStatus;const oldStatus=original.runtime?.status;original.runtimeStatus='ACTIVE';if(original.runtime)original.runtime.status='ACTIVE';let calls=0;const o=new Orchestrator(second,{execute:async()=>{calls++;return {kind:'success',output:{objective:'x',requirements:[],constraints:[],affected_components:[],security_requirements:[],test_requirements:[],acceptance_criteria:[],validation_required:false,validation_reason:''},externalExecutionId:'external'}}} as any,{} as any,{} as any,{} as any);const context={principal,operation:'run',requestId:w.requestId,workflowId:w.id,specialistId:w.logicalSpecialistId,executionType:'specialist',effectiveClassification:'PUBLIC',resolvedRepository:repository,authorizationDecision:{allowed:true,ruleId:'test',decidedAt:new Date().toISOString()}};await o.run(w.id,context,'worker');await Promise.all([o.run(w.id,context,'worker'),o.run(w.id,context,'worker')]);original.runtimeStatus=oldRuntimeStatus;if(original.runtime)original.runtime.status=oldStatus;assert.equal(calls,1);const attempts=await second.getAttempts(w.id);assert.equal(attempts.length,1);assert.equal(attempts[0].state,'SUCCEEDED');assert.ok(attempts[0].initiationEvidence);}finally{await second.pool.end();}});
