// @ts-nocheck
import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { PgStore } from '../src/pg-store.js';

const url=process.env.PG_TEST_URL;const id=()=>randomUUID();const makeStore=()=>new PgStore(url);
const input=(requestId=id())=>({requestId,workflowType:'software' as const,logicalSpecialistId:'architecture-security-advisor',runtimeId:'runtime',validationRequired:true,effectiveClassification:'PUBLIC' as const,objective:'task22e',context:{principal:{id:'local-test-principal',roles:[],scopes:[],authType:'token' as const}},requiresImplementation:true});
const approval=(workflowId,overrides={})=>({workflowId,protectedActionId:'protected-stage',scopeFingerprint:'scope-v1',reason:'external access changes',categories:['EXTERNAL_ACCESS'],...overrides});
const setup=async()=>{const store=makeStore();const workflow=await store.createWorkflow(input(),'task22e','create');return {store,workflow};};

test('Task 22E creates pending approval atomically and validates material categories', {skip:!url}, async()=>{const {store,workflow}=await setup();try{const a=await store.createPendingApproval(approval(workflow.id));assert.equal(a.status,'PENDING');assert.equal((await store.getWorkflow(workflow.id)).status,'AWAITING_APPROVAL');assert.deepEqual(a.categories,['EXTERNAL_ACCESS']);await assert.rejects(()=>store.createPendingApproval(approval(workflow.id,{categories:['INVALID']})),/INVALID_APPROVAL_CATEGORY|INVALID_STATE_TRANSITION|workflow_approvals/);await assert.rejects(()=>store.createPendingApproval(approval(workflow.id,{protectedActionId:'other'})),/INVALID_STATE_TRANSITION|workflow_approvals/);}finally{await store.pool.end();}});

test('Task 22E approval creation rolls back on audit failure', {skip:!url}, async()=>{const {store,workflow}=await setup();try{const original=store.event;store.event=async()=>{throw new Error('TASK22E_APPROVAL_AUDIT_FAIL');};await assert.rejects(()=>store.createPendingApproval(approval(workflow.id)),/TASK22E_APPROVAL_AUDIT_FAIL/);store.event=original;assert.equal(await store.getPendingApproval(workflow.id),undefined);assert.equal((await store.getWorkflow(workflow.id)).status,'ROUTED');}finally{await store.pool.end();}});

test('Task 22E approval decision is durable, audited, and idempotent', {skip:!url}, async()=>{const {store,workflow}=await setup();try{const a=await store.createPendingApproval(approval(workflow.id));const approved=await store.decideApproval(a.id,'APPROVED','approved for production','approver-1');assert.equal(approved.status,'APPROVED');assert.equal(approved.decidedBy,'approver-1');assert.ok(approved.decidedAt);assert.equal((await store.getWorkflow(workflow.id)).status,'ROUTED');assert.equal((await store.decideApproval(a.id,'APPROVED','different','approver-2')).decidedBy,'approver-1');await assert.rejects(()=>store.decideApproval(a.id,'REJECTED','no'),/APPROVAL_ALREADY_DECIDED/);const events=await store.getEvents(workflow.id);assert.ok(events.some(x=>x.actorId==='approval-requested'));assert.ok(events.some(x=>x.actorId==='approval-approved'));}finally{await store.pool.end();}});

test('Task 22E rejection survives restart and never permits the protected claim', {skip:!url}, async()=>{const first=makeStore();const workflow=await first.createWorkflow(input(),'task22e','reject');const a=await first.createPendingApproval(approval(workflow.id));await first.decideApproval(a.id,'REJECTED','not authorized','approver-1');await first.pool.end();const second=makeStore();try{assert.equal((await second.getApproval(a.id)).status,'REJECTED');assert.equal((await second.getWorkflow(workflow.id)).status,'FAILED');await assert.rejects(()=>second.claimStage(workflow.id,'protected-stage','specialist','runtime','worker'),/WORKFLOW_NOT_ACTIVE/);}finally{await second.pool.end();}});

test('Task 22E prevents stale approved scope reuse', {skip:!url}, async()=>{const {store,workflow}=await setup();try{const a=await store.createPendingApproval(approval(workflow.id));await store.decideApproval(a.id,'APPROVED');assert.ok(await store.getApprovedApproval(workflow.id,'protected-stage','scope-v1'));await assert.rejects(()=>store.getApprovedApproval(workflow.id,'protected-stage','scope-v2'),/APPROVAL_SCOPE_MISMATCH/);}finally{await store.pool.end();}});

test('Task 22E concurrent approval decisions have one winner', {skip:!url}, async()=>{const {store,workflow}=await setup();try{const a=await store.createPendingApproval(approval(workflow.id));const results=await Promise.allSettled([store.decideApproval(a.id,'APPROVED','yes','a'),store.decideApproval(a.id,'REJECTED','no','b')]);assert.equal(results.filter(x=>x.status==='fulfilled').length,1);assert.equal(results.filter(x=>x.status==='rejected').length,1);assert.ok(['APPROVED','REJECTED'].includes((await store.getApproval(a.id)).status));}finally{await store.pool.end();}});
