import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { createServer } from 'node:http';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import test from 'node:test';

const require=createRequire(import.meta.url);
let playwright:any;
try{playwright=require('playwright');}catch{playwright=undefined;}

if(!playwright){
  test('Task 27 browser acceptance requires Playwright and a browser binary',{skip:'Playwright is not installed in this environment'},()=>{});
}else{
  test('MVP browser journey completes a multi-specialist manual stage return',async()=>{
    let stageComplete=false;const workflowId='task27-browser-workflow';const planId='task27-browser-plan';const stageId='task27-browser-stage';
    const workflow=()=>({id:workflowId,requestId:'task27-browser-request',workflowType:'non_code',objective:'review security and repository configuration',status:stageComplete?'SPECIALIST_RUNNING':'MANUAL_HANDOFF_REQUIRED',routingConfidence:'CLEAR',selectedSpecialistId:'architecture-security-advisor',runtime:{status:'MANUAL_ONLY',runtimeId:null,executable:false},execution:{started:false,completed:false,manualHandoffRequired:!stageComplete},clarificationRequired:false,approvalRequired:false,createdAt:'2026-09-19T00:00:00.000Z',updatedAt:'2026-09-19T00:00:00.000Z',orchestrationPlan:{plan:{id:planId,workflowId,version:1,status:stageComplete?'RUNNING':'MANUAL_HANDOFF_REQUIRED',reason:'collective coverage'},stages:[{id:stageId,planId,workflowId,specialistId:'architecture-security-advisor',purpose:'Review security constraints',dependencies:[],status:stageComplete?'COMPLETE':'MANUAL_HANDOFF_REQUIRED',order:0,manualHandoff:{available:!stageComplete,specialistId:'architecture-security-advisor',specialistName:'Architecture & Security Advisor',navigationUrl:'https://chatgpt.com/g/g-task27',expectedOutput:'A bounded review result',instructions:'Return the review result',returnEndpoint:`/v1/workflows/${workflowId}/plans/${planId}/stages/${stageId}/handoff-response`}}]}});
    const server=createServer((req,res)=>{const send=(status:number,body:unknown,content='application/json')=>{res.writeHead(status,{'content-type':content});res.end(content==='application/json'?JSON.stringify(body):String(body));};const path=req.url??'';if(req.method==='GET'&&path==='/'){return send(200,readFileSync(resolve(process.cwd(),'client/index.html'),'utf8'),'text/html');}if(req.method==='GET'&&path==='/app.js'){return send(200,readFileSync(resolve(process.cwd(),'client/app.js'),'utf8'),'text/javascript');}if(req.method==='GET'&&path==='/styles.css'){return send(200,readFileSync(resolve(process.cwd(),'client/styles.css'),'utf8'),'text/css');}if(req.method==='POST'&&path==='/v1/workflows'){return send(201,workflow());}if(req.method==='GET'&&path===`/v1/workflows/${workflowId}`){return send(200,workflow());}if(req.method==='GET'&&path===`/v1/specialists/architecture-security-advisor`){return send(200,{id:'architecture-security-advisor',origin:'BUILTIN',displayName:'Architecture & Security Advisor',runtime:{status:'MANUAL_ONLY',executable:false},manualHandoff:{available:true,navigationUrl:'https://chatgpt.com/g/g-task27'}});}if(req.method==='GET'&&path===`/v1/workflows/${workflowId}/events`){return send(200,[]);}if(req.method==='POST'&&path===`/v1/workflows/${workflowId}/plans/${planId}/stages/${stageId}/handoff-response`){stageComplete=true;return send(200,workflow());}send(404,{error:'NOT_FOUND'});});
    await new Promise<void>(resolveListen=>server.listen(0,'127.0.0.1',()=>resolveListen()));const address=server.address();assert.ok(address&&typeof address==='object');const browser=await playwright.chromium.launch({headless:true});try{const page=await browser.newPage();await page.goto(`http://127.0.0.1:${address.port}/`);await page.locator('#repository').fill('browser-repo');await page.locator('#objective').fill('review security and repository configuration');await page.locator('#task-form button[type="submit"]').click();await page.locator('.stage-handoff').waitFor();assert.match(await page.locator('#workflow-panel').textContent(),/Architecture & Security Advisor/);assert.match(await page.locator('#workflow-panel').textContent(),/Copy stage handoff context/);await page.locator('.stage-handoff textarea').fill('{"summary":"completed"}');await page.locator('.stage-handoff button', {hasText:'Submit stage output'}).click();await page.waitForTimeout(50);assert.match(await page.locator('#workflow-panel').textContent(),/COMPLETE|Specialist complete|Continue workflow/);assert.doesNotMatch(await page.locator('#workflow-panel').textContent(),/Submit stage output/);}finally{await browser.close();await new Promise<void>(resolveClose=>server.close(()=>resolveClose()));}
  });
}
