// @ts-nocheck
import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { spawn } from 'node:child_process';
import { PgStore } from '../src/pg-store.js';
import { persistResolvedRouting } from '../src/routing.js';

const url=process.env.PG_TEST_URL; const id=()=>randomUUID();
const repository={repo:{source:'./repo',classification:'PUBLIC',allowedCallers:['m5-user'],allowedSpecialists:['architecture-security-advisor'],allowedExecutionTypes:['specialist'],allowedRefs:['main']}};
const env=port=>({...process.env,APP_MODE:'deployed',AUTH_MODE:'token',DATABASE_URL:url,PGPASSWORD:process.env.PGPASSWORD,ORCHESTRATOR_API_TOKEN:'test-only-token',AUTH_PRINCIPALS:JSON.stringify({'test-only-token':{id:'m5-user',roles:[],scopes:[]}}),ALLOWED_REPOSITORIES:JSON.stringify(repository),PORT:String(port)});
const start=port=>{const child=spawn(process.execPath,['dist/src/server.js'],{env:env(port),stdio:['ignore','pipe','pipe']});return new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('SERVER_START_TIMEOUT')),5000);child.stdout.on('data',chunk=>{if(String(chunk).includes('server_started')){clearTimeout(timer);resolve(child);}});child.on('error',reject);});};
const stop=child=>new Promise(resolve=>{child.once('exit',resolve);child.kill('SIGTERM');});
const get=(port,path)=>fetch(`http://127.0.0.1:${port}${path}`,{headers:{authorization:'Bearer test-only-token'}});
const post=(port,path,body)=>fetch(`http://127.0.0.1:${port}${path}`,{method:'POST',headers:{authorization:'Bearer test-only-token','content-type':'application/json'},body:JSON.stringify(body)});
const forbidden=['authorizationDecision','ExecutionContext','OPENAI_API_KEY','container','instructionRef','outputSchema','timeoutSeconds','maxAttempts','secret','password','apiKey','environment'];
const assertSafe=body=>{const serialized=JSON.stringify(body);for(const field of forbidden)assert.equal(serialized.toLowerCase().includes(field.toLowerCase()),false,field);};

test('22M5-01/02/03/04/07/08/11/12 complete public API contract is consistent and restart-safe',{skip:!url},async()=>{
  const requestId=id();const first=await start(18150);let workflowId;let before;
  try{
    const createdResponse=await post(18150,'/v1/workflows',{request_id:requestId,workflow_type:'non_code',objective:'architecture security review',repository:'repo'});assert.equal(createdResponse.status,201);const created=await createdResponse.json();workflowId=created.id;assert.equal(created.status,'ROUTED');assert.equal(created.selectedSpecialistId,'architecture-security-advisor');assert.equal(created.execution.started,false);assert.equal(created.execution.completed,false);assertSafe(created);
    const workflow=await (await get(18150,`/v1/workflows/${workflowId}`)).json();const history=await (await get(18150,`/v1/workflows/${workflowId}/routing-decisions`)).json();const specialists=await (await get(18150,'/v1/specialists')).json();const specialist=await (await get(18150,'/v1/specialists/architecture-security-advisor')).json();
    assert.equal(workflow.selectedSpecialistId,history.find(x=>x.current).selectedSpecialistId);assert.equal(workflow.routingConfidence,history.find(x=>x.current).routingConfidence);assert.equal(workflow.selectedSpecialistId,specialist.id);assert.equal(workflow.runtime.status,specialist.runtime.status);assert.equal(workflow.runtime.executable,specialist.runtime.executable);assert.equal(specialists.some(x=>x.id===specialist.id),true);assertSafe(workflow);assertSafe(history);assertSafe(specialists);assertSafe(specialist);
    const unknown=await get(18150,`/v1/specialists/${id()}`);assert.equal(unknown.status,404);const unknownWorkflow=await get(18150,`/v1/workflows/${id()}`);assert.equal(unknownWorkflow.status,404);const unknownHistory=await get(18150,`/v1/workflows/${id()}/routing-decisions`);assert.equal(unknownHistory.status,404);
    const store=new PgStore(url);before={workflow:await store.getWorkflow(workflowId),history:await store.getRoutingHistory(workflowId),attempts:await store.getAttempts(workflowId),artifacts:await store.getArtifacts(workflowId),events:await store.getEvents(workflowId),approvals:await store.getApprovalHistory(workflowId)};await store.pool.end();
    for(const path of [`/v1/workflows/${workflowId}`,`/v1/workflows/${workflowId}/routing-decisions`,'/v1/specialists','/v1/specialists/architecture-security-advisor']){const response=await get(18150,path);assert.equal(response.status,200);await response.json();}
    const afterStore=new PgStore(url);const after={workflow:await afterStore.getWorkflow(workflowId),history:await afterStore.getRoutingHistory(workflowId),attempts:await afterStore.getAttempts(workflowId),artifacts:await afterStore.getArtifacts(workflowId),events:await afterStore.getEvents(workflowId),approvals:await afterStore.getApprovalHistory(workflowId)};await afterStore.pool.end();assert.deepEqual(after,before);
  }finally{await stop(first);}
  const second=await start(18151);try{const workflow=await (await get(18151,`/v1/workflows/${workflowId}`)).json();const history=await (await get(18151,`/v1/workflows/${workflowId}/routing-decisions`)).json();const specialist=await (await get(18151,`/v1/specialists/${workflow.selectedSpecialistId}`)).json();assert.equal(workflow.id,workflowId);assert.equal(history.length,1);assert.equal(history[0].current,true);assert.equal(workflow.selectedSpecialistId,history[0].selectedSpecialistId);assert.equal(workflow.runtime.status,specialist.runtime.status);assert.equal(workflow.execution.started,false);assert.equal(workflow.execution.completed,false);}finally{await stop(second);}
});

test('22M5-05/06/07 public continuation rejects forged authority and illegal transitions with zero effects',{skip:!url},async()=>{
  const store=new PgStore(url);const workflow=await store.createWorkflow({requestId:id(),workflowType:'non_code',logicalSpecialistId:null,runtimeId:undefined,validationRequired:false,effectiveClassification:'PUBLIC',objective:'clarification security',context:{},requiresImplementation:false},'m5','clarification');const initial=await persistResolvedRouting(store,workflow.id,{routingConfidence:'AMBIGUOUS',selectedSpecialistId:null,routingReason:'ambiguous',candidates:[{specialistId:'architecture-security-advisor',rank:1,matchReason:'architecture',evidence:{specialistId:'architecture-security-advisor',registryVersion:'1',ownershipMatches:['architecture'],capabilityMatches:[],workflowRelationship:'none',exclusionResult:'eligible',specificity:2,runtimeStatus:'ACTIVE',matchReason:'architecture'}},{specialistId:'other',rank:2,matchReason:'other',evidence:{specialistId:'other',registryVersion:'1',ownershipMatches:['other'],capabilityMatches:[],workflowRelationship:'none',exclusionResult:'eligible',specificity:2,runtimeStatus:'ACTIVE',matchReason:'other'}}],requiresClarification:true,clarificationQuestion:'Which specialist?'});await store.pool.end();const child=await start(18152);
  try{const beforeStore=new PgStore(url);const before={workflow:await beforeStore.getWorkflow(workflow.id),history:await beforeStore.getRoutingHistory(workflow.id),attempts:await beforeStore.getAttempts(workflow.id),artifacts:await beforeStore.getArtifacts(workflow.id)};await beforeStore.pool.end();const forged=await post(18152,`/v1/workflows/${workflow.id}/clarification-response`,{clarificationId:initial.clarification.id,response:'security architecture',logicalSpecialistId:'forged',runtimeId:'forged',workflowStatus:'COMPLETE',routingConfidence:'CLEAR',executionEvidence:{forged:true},principal:{id:'attacker'},executionContext:{specialistId:'forged'}});assert.equal(forged.status,400);const afterStore=new PgStore(url);const after={workflow:await afterStore.getWorkflow(workflow.id),history:await afterStore.getRoutingHistory(workflow.id),attempts:await afterStore.getAttempts(workflow.id),artifacts:await afterStore.getArtifacts(workflow.id)};await afterStore.pool.end();assert.deepEqual(after,before);
    const valid=await post(18152,`/v1/workflows/${workflow.id}/clarification-response`,{clarificationId:initial.clarification.id,response:'security architecture',routing:{selectedSpecialistId:'forged-specialist',routingConfidence:'CLEAR',routingReason:'forged'}});assert.equal(valid.status,200);const routed=await valid.json();assert.equal(routed.selectedSpecialistId,'architecture-security-advisor');assert.equal(routed.execution.started,false);const duplicate=await post(18152,`/v1/workflows/${workflow.id}/clarification-response`,{clarificationId:initial.clarification.id,response:'again'});assert.equal(duplicate.status,400);const finalStore=new PgStore(url);assert.equal((await finalStore.getRoutingHistory(workflow.id)).length,2);assert.equal((await finalStore.getAttempts(workflow.id)).length,0);assert.equal((await finalStore.getArtifacts(workflow.id)).length,0);await finalStore.pool.end();
  }finally{await stop(child);}
});

test('22M5-09/10 approval integration and legacy clarification/approval reads remain compatible',{skip:!url},async()=>{
  const store=new PgStore(url);const approvalWorkflow=await store.createWorkflow({requestId:id(),workflowType:'software',logicalSpecialistId:'architecture-security-advisor',runtimeId:'runtime',validationRequired:true,effectiveClassification:'PUBLIC',objective:'approval acceptance',context:{},requiresImplementation:true},'m5','approval');const approval=await store.createPendingApproval({workflowId:approvalWorkflow.id,protectedActionId:'protected-stage',scopeFingerprint:'scope-v1',reason:'approval acceptance',categories:['EXECUTION_RISK']});const clarificationWorkflow=await store.createWorkflow({requestId:id(),workflowType:'non_code',logicalSpecialistId:'architecture-security-advisor',runtimeId:'runtime',validationRequired:false,effectiveClassification:'PUBLIC',objective:'legacy clarification',context:{},requiresImplementation:false},'m5','legacy');const decision={id:id(),workflowId:clarificationWorkflow.id,selectedSpecialistId:null,routingConfidence:'AMBIGUOUS',routingReason:'ambiguous',decisionType:'INITIAL',supersedesDecisionId:null,createdAt:new Date().toISOString()};await store.recordRoutingDecision(decision);const clarification=await store.createPendingClarification({workflowId:clarificationWorkflow.id,routingDecisionId:decision.id,question:'Which owner?'});await store.pool.end();const child=await start(18153);
  try{const legacyApproval=await get(18153,`/v1/workflows/${approvalWorkflow.id}/approval`);assert.equal(legacyApproval.status,200);assert.equal((await legacyApproval.json()).id,approval.id);const legacyClarification=await get(18153,`/v1/workflows/${clarificationWorkflow.id}/clarification`);assert.equal(legacyClarification.status,200);assert.equal((await legacyClarification.json()).id,clarification.id);const approved=await post(18153,`/v1/workflows/${approvalWorkflow.id}/approval`,{approvalId:approval.id,decision:'APPROVED',reason:'approved'});assert.equal(approved.status,200);const body=await approved.json();assert.equal(body.status,'APPROVED');assert.equal(body.workflow.status,'ROUTED');assert.equal(body.workflow.execution.started,false);const duplicate=await post(18153,`/v1/workflows/${approvalWorkflow.id}/approval`,{approvalId:approval.id,decision:'REJECTED'});assert.equal(duplicate.status,400);const illegal=await post(18153,`/v1/workflows/${approvalWorkflow.id}/approval`,{decision:'APPROVED'});assert.equal(illegal.status,400);}finally{await stop(child);}
});
