// @ts-nocheck
import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { PgStore } from '../src/pg-store.js';

const url=process.env.PG_TEST_URL;
const makeStore=()=>new PgStore(url);
const id=()=>randomUUID();
const input=(requestId=id())=>({requestId,workflowType:'software' as const,logicalSpecialistId:'architecture-security-advisor',runtimeId:'runtime',validationRequired:true,effectiveClassification:'PUBLIC' as const,objective:'task22d',context:{},requiresImplementation:true});
const setup=async()=>{const store=makeStore();const workflow=await store.createWorkflow(input(),'task22d','create');const decision={id:id(),workflowId:workflow.id,selectedSpecialistId:null,routingConfidence:'AMBIGUOUS' as const,routingReason:'two plausible owners',decisionType:'INITIAL' as const,supersedesDecisionId:null,createdAt:new Date().toISOString()};await store.recordRoutingDecisionWithCandidates(decision,[{id:id(),routingDecisionId:decision.id,specialistId:'one',rank:1,matchReason:'first'},{id:id(),routingDecisionId:decision.id,specialistId:'two',rank:2,matchReason:'second'}]);return {store,workflow,decision};};
const pendingInput=(workflow,decision)=>({workflowId:workflow.id,routingDecisionId:decision.id,question:'Which deployment target is authoritative?'});

test('Task 22D creates pending clarification atomically and rejects invalid relationships', {skip:!url}, async()=>{const {store,workflow,decision}=await setup();try{const c=await store.createPendingClarification(pendingInput(workflow,decision));assert.equal(c.status,'PENDING');assert.equal((await store.getWorkflow(workflow.id)).status,'AWAITING_CLARIFICATION');assert.equal((await store.getPendingClarification(workflow.id)).question,c.question);await assert.rejects(()=>store.createPendingClarification(pendingInput(workflow,decision)),/INVALID_STATE_TRANSITION|routing_clarifications/);const other=await store.createWorkflow(input(),'task22d','other');await assert.rejects(()=>store.createPendingClarification({workflowId:other.id,routingDecisionId:decision.id,question:'wrong workflow'}),/CLARIFICATION_WORKFLOW_MISMATCH/);}finally{await store.pool.end();}});

test('Task 22D requires an AMBIGUOUS triggering decision and rolls back on transition failure', {skip:!url}, async()=>{const {store,workflow,decision}=await setup();try{const clear={...decision,id:id(),routingConfidence:'CLEAR',routingReason:'clear'};await store.recordRoutingDecision(clear);await assert.rejects(()=>store.createPendingClarification({workflowId:workflow.id,routingDecisionId:clear.id,question:'not ambiguous'}),/CLARIFICATION_REQUIRES_AMBIGUOUS_DECISION/);const original=store.event;store.event=async()=>{throw new Error('TASK22D_TRANSITION_FAIL');};await assert.rejects(()=>store.createPendingClarification(pendingInput(workflow,decision)),/TASK22D_TRANSITION_FAIL/);store.event=original;assert.equal((await store.getWorkflow(workflow.id)).status,'ROUTED');assert.equal(await store.getPendingClarification(workflow.id),undefined);}finally{await store.pool.end();}});

test('Task 22D persists response once and rejects duplicate answers', {skip:!url}, async()=>{const {store,workflow,decision}=await setup();try{const c=await store.createPendingClarification(pendingInput(workflow,decision));const answered=await store.recordClarificationResponse(c.id,'production is authoritative');assert.equal(answered.status,'ANSWERED');assert.equal(answered.response,'production is authoritative');assert.ok(answered.answeredAt);await assert.rejects(()=>store.recordClarificationResponse(c.id,'changed'),/CLARIFICATION_ALREADY_ANSWERED/);}finally{await store.pool.end();}});

test('Task 22D answers concurrently exactly once', {skip:!url}, async()=>{const {store,workflow,decision}=await setup();try{const c=await store.createPendingClarification(pendingInput(workflow,decision));const results=await Promise.allSettled([store.recordClarificationResponse(c.id,'answer one'),store.recordClarificationResponse(c.id,'answer two')]);assert.equal(results.filter(x=>x.status==='fulfilled').length,1);assert.equal(results.filter(x=>x.status==='rejected').length,1);assert.equal((await store.getClarification(c.id)).status,'ANSWERED');}finally{await store.pool.end();}});

test('Task 22D resumes from answered clarification with new historical decision and survives restart', {skip:!url}, async()=>{const first=makeStore();const workflow=await first.createWorkflow(input(),'task22d','resume');const original={id:id(),workflowId:workflow.id,selectedSpecialistId:null,routingConfidence:'AMBIGUOUS' as const,routingReason:'ambiguous',decisionType:'INITIAL' as const,supersedesDecisionId:null,createdAt:'2026-09-11T00:00:00.000Z'};await first.recordRoutingDecisionWithCandidates(original,[{id:id(),routingDecisionId:original.id,specialistId:'one',rank:1,matchReason:'possible'}]);const clarification=await first.createPendingClarification(pendingInput(workflow,original));await first.recordClarificationResponse(clarification.id,'use the production target');await first.pool.end();const second=makeStore();try{const resumed={id:id(),workflowId:workflow.id,selectedSpecialistId:'architecture-security-advisor',routingConfidence:'PROBABLE' as const,routingReason:'clarified production target',decisionType:'POST_CLARIFICATION' as const,supersedesDecisionId:original.id,createdAt:'2026-09-11T00:00:01.000Z'};const result=await second.resumeClarification(workflow.id,clarification.id,resumed,[{id:id(),routingDecisionId:resumed.id,specialistId:'architecture-security-advisor',rank:1,matchReason:'clarified'}]);assert.equal(result.workflow.status,'ROUTED');assert.equal((await second.getClarification(clarification.id)).status,'ANSWERED');assert.equal((await second.getRoutingDecision(original.id)).routingConfidence,'AMBIGUOUS');assert.equal((await second.getLatestRoutingDecision(workflow.id)).id,resumed.id);assert.equal((await second.getRoutingCandidates(original.id)).length,1);assert.equal((await second.getRoutingCandidates(resumed.id)).length,1);const retry=await second.resumeClarification(workflow.id,clarification.id,{...resumed,id:id()},[]);assert.equal(retry.decision.id,resumed.id);}finally{await second.pool.end();}});

test('Task 22D prevents direct specialist claims while PostgreSQL workflow waits', {skip:!url}, async()=>{const {store,workflow,decision}=await setup();try{await store.createPendingClarification(pendingInput(workflow,decision));await assert.rejects(()=>store.claimStage(workflow.id,'specialist:architecture-security-advisor','specialist','runtime','worker'),/CLARIFICATION_REQUIRED/);assert.equal((await store.getAttempts(workflow.id)).length,0);}finally{await store.pool.end();}});
