import test from 'node:test';
import assert from 'node:assert/strict';
import { MATERIAL_APPROVAL_CATEGORIES, NO_MATCH_FALLBACK_ORDER, ROUTING_CONFIDENCES, ROUTING_DECISION_TYPES, assertTransition } from '../src/domain.js';
import { registry, validateRegistry } from '../src/registry.js';

test('routing contracts expose every approved value',()=>{assert.deepEqual(ROUTING_CONFIDENCES,['CLEAR','PROBABLE','AMBIGUOUS','NO_MATCH']);assert.deepEqual(ROUTING_DECISION_TYPES,['INITIAL','POST_CLARIFICATION','USER_OVERRIDE','DOWNSTREAM_ROUTE','FALLBACK']);assert.deepEqual(MATERIAL_APPROVAL_CATEGORIES,['SCOPE','AUTHORITY','COST','EXTERNAL_ACCESS','SECURITY_PRIVACY','EXECUTION_RISK']);});
test('routing confidence is independent from workflow state',()=>{assertTransition('ROUTED','AWAITING_CLARIFICATION');assertTransition('ROUTED','AWAITING_APPROVAL');assert.notEqual('CLEAR','ROUTED');});
test('blocking states do not execute specialist work directly',()=>{assert.throws(()=>assertTransition('AWAITING_CLARIFICATION','SPECIALIST_RUNNING'),/INVALID_STATE_TRANSITION/);assert.throws(()=>assertTransition('AWAITING_APPROVAL','SPECIALIST_RUNNING'),/INVALID_STATE_TRANSITION/);});
test('canonical registry validates and supports the configured specialist contract',()=>{validateRegistry(registry);const s=registry['architecture-security-advisor'];assert.equal(s.id,s.specialistId);assert.ok(s.primaryOwnership.length);assert.ok(s.capabilities.length);assert.ok(Array.isArray(s.exclusions));assert.ok(Array.isArray(s.overlapsWith));assert.ok(Array.isArray(s.upstreamSpecialists));assert.ok(Array.isArray(s.downstreamSpecialists));assert.equal(s.runtimeStatus,s.runtime?.status);});
test('registry validation rejects duplicate IDs, runtimes, references, and malformed metadata',()=>{const base=structuredClone(registry);const duplicate={...base,'copy':{...base['architecture-security-advisor'],id:'architecture-security-advisor'}};assert.throws(()=>validateRegistry(duplicate),/DUPLICATE_SPECIALIST_ID/);const runtime={...base,'copy':{...base['architecture-security-advisor'],id:'copy',specialistId:'copy'}};assert.throws(()=>validateRegistry(runtime),/DUPLICATE_RUNTIME_ID/);const ref={...base,'architecture-security-advisor':{...base['architecture-security-advisor'],overlapsWith:['missing']}};assert.throws(()=>validateRegistry(ref),/INVALID_SPECIALIST_REFERENCE/);const malformed={...base,'architecture-security-advisor':{...base['architecture-security-advisor'],lastReviewedAt:'not-a-date'}};assert.throws(()=>validateRegistry(malformed),/INVALID_LAST_REVIEWED_AT/);});
test('legitimate overlap and logical/runtime separation remain representable',()=>{const a=structuredClone(registry);a['second']={...a['architecture-security-advisor'],id:'second',specialistId:'second',runtimeId:null,runtime:undefined,overlapsWith:['architecture-security-advisor'],primaryOwnership:['second-domain']};a['architecture-security-advisor'].overlapsWith=['second'];assert.doesNotThrow(()=>validateRegistry(a));assert.notEqual(a.second.id,a.second.runtimeId);assert.deepEqual(NO_MATCH_FALLBACK_ORDER,['NO_MATCH','FOCUSED_CLARIFICATION','APPROVED_GENERAL_FALLBACK','EXPLICIT_NO_OWNER_RESULT']);});
