import { CodexPrompt, SoftwareOutput, ValidationOutput, validSoftwareOutput, validValidation } from './domain.js';
import { ExecutionContext, assertAuthorizedExecution } from './trust.js';
import { resolveRoutableSpecialist } from './registry.js';
import { spawn } from 'node:child_process';
import { randomUUID } from 'node:crypto';
import { realpath, mkdir, mkdtemp, rm } from 'node:fs/promises';
import { join, relative, resolve, sep } from 'node:path';

export interface ExecResult<T>{kind:string;output?:T;externalExecutionId?:string;errorCode?:string;errorMessage?:string;usageMetadata?:unknown;}
type InitiationHook=(e:unknown)=>void;
type FetchLike=(input:RequestInfo|URL,init?:RequestInit)=>Promise<Response>;
type SpawnLike=(command:string,args:string[],options:unknown)=>any;
type WorkspaceLike={path:string;cleanup:()=>Promise<void>};
export interface SpecialistExecutor{execute(input:{trustedContext:ExecutionContext;workflowId:string;stageId:string;runtimeId:string;runtimeVersion:string;objective:string;context:unknown;expectedOutputSchema:string;onInitiation?:InitiationHook}):Promise<ExecResult<any>>;}
export interface PromptBuilderExecutor{execute(input:{trustedContext:ExecutionContext;objective:string;requirements:SoftwareOutput}):Promise<ExecResult<CodexPrompt>>;}
export interface CodexExecutor{execute(input:{trustedContext:ExecutionContext;workflowId:string;stageId:string;promptArtifact:CodexPrompt;executionPolicy:unknown;onInitiation?:InitiationHook}):Promise<ExecResult<any>>;}
export interface ValidationExecutor{execute(input:{trustedContext:ExecutionContext;workflowId:string;stageId:string;originalRequirements:SoftwareOutput;codexPrompt:CodexPrompt;codexResult:unknown;changedFiles:string[];testResults:unknown[];onInitiation?:InitiationHook}):Promise<ExecResult<any>>;}
export class UnavailableSpecialist implements SpecialistExecutor{async execute(){return {kind:'terminal_failure',errorCode:'DEPENDENCY_UNAVAILABLE',errorMessage:'Specialist runtime is not configured'} as ExecResult<SoftwareOutput>;}}
export class SafePromptBuilder implements PromptBuilderExecutor{async execute(i:{trustedContext:ExecutionContext;objective:string;requirements:SoftwareOutput}){assertAuthorizedExecution(i.trustedContext);return {kind:'success',output:{task_summary:i.objective,implementation_instructions:i.requirements.requirements.join('\n'),scope_constraints:i.requirements.constraints,tests_required:i.requirements.test_requirements,acceptance_criteria:i.requirements.acceptance_criteria,expected_result_report:['changed files','tests','risks']}} as ExecResult<CodexPrompt>;}}
export class UnavailableCodex implements CodexExecutor{async execute(){return {kind:'terminal_failure',errorCode:'CODEX_EXECUTION_FAILED',errorMessage:'Codex executor is not configured'} as ExecResult<any>;}}
export class UnavailableValidation implements ValidationExecutor{async execute(){return {kind:'terminal_failure',errorCode:'DEPENDENCY_UNAVAILABLE',errorMessage:'Validation runtime is not configured'} as ExecResult<ValidationOutput>;}}
function retryable(s:number){return s===408||s===409||s===429||s>=500;}
async function backoff(n:number){await new Promise(r=>setTimeout(r,Math.min(2000,100*2**n)+Math.floor(Math.random()*100)));}
function responseText(body:any){return body.output_text??body.output?.flatMap((x:any)=>x.content??[]).find((x:any)=>x.text)?.text;}
const MAX_PROVIDER_RESPONSE_BYTES=4*1024*1024;
const MAX_PROCESS_OUTPUT_BYTES=4*1024*1024;
const EXTERNAL_EXECUTION_TIMEOUT_MS=15*60*1000;
async function responseJson(response:Response){
  if(!response.body){const text=await response.text();if(Buffer.byteLength(text,'utf8')>MAX_PROVIDER_RESPONSE_BYTES)throw new Error('PROVIDER_RESPONSE_TOO_LARGE');return JSON.parse(text);}
  const reader=response.body.getReader();const chunks:Buffer[]=[];let size=0;
  try{while(true){const part=await reader.read();if(part.done)break;const chunk=Buffer.from(part.value);size+=chunk.byteLength;if(size>MAX_PROVIDER_RESPONSE_BYTES)throw new Error('PROVIDER_RESPONSE_TOO_LARGE');chunks.push(chunk);}}
  finally{reader.releaseLock();}
  return JSON.parse(Buffer.concat(chunks).toString('utf8'));
}
function captureProcess(p:any,timeoutMs=EXTERNAL_EXECUTION_TIMEOUT_MS):Promise<{code:number;out:string}>{
  return new Promise((resolve,reject)=>{
    let out='';let bytes=0;let settled=false;
    const finish=(fn:(value:any)=>void,value:any)=>{if(settled)return;settled=true;clearTimeout(timer);fn(value);};
    const fail=(error:unknown)=>{try{p.kill?.('SIGKILL');}catch{}finish(reject,error);};
    const append=(data:any)=>{const text=String(data);bytes+=Buffer.byteLength(text,'utf8');if(bytes>MAX_PROCESS_OUTPUT_BYTES){fail(new Error('EXECUTOR_OUTPUT_LIMIT'));return;}out+=text;};
    const timer=setTimeout(()=>fail(new Error('EXECUTOR_TIMEOUT')),timeoutMs);
    p.stdout?.on('data',append);p.stderr?.on('data',append);p.once('error',(error:unknown)=>finish(reject,error));p.once('exit',(code:number|null)=>finish(resolve,{code:code??1,out}));
  });
}
function assertSpecialistRuntime(input:Parameters<SpecialistExecutor['execute']>[0]){assertAuthorizedExecution(input.trustedContext);const runtime=resolveRoutableSpecialist(input.trustedContext.specialistId)?.runtime;if(!runtime||input.runtimeId!==runtime.runtimeId||input.runtimeVersion!==runtime.version||input.expectedOutputSchema!==runtime.outputSchema)throw new Error('AUTHORIZATION_FAILED');}
export class OpenAISpecialistExecutor implements SpecialistExecutor{
  constructor(private apiKey:string,private model=process.env.OPENAI_MODEL??'gpt-4.1-mini',private fetchImpl:FetchLike=fetch){}
  async execute(i:Parameters<SpecialistExecutor['execute']>[0]){assertSpecialistRuntime(i);for(let n=0;n<2;n++){try{assertSpecialistRuntime(i);const request=this.fetchImpl('https://api.openai.com/v1/responses',{method:'POST',headers:{authorization:`Bearer ${this.apiKey}`,'content-type':'application/json'},signal:AbortSignal.timeout(120000),body:JSON.stringify({model:this.model,input:[{role:'system',content:`Return only JSON matching ${i.expectedOutputSchema}.`},{role:'user',content:JSON.stringify({objective:i.objective,context:i.context})}],text:{format:{type:'json_object'}}})});await i.onInitiation?.({provider:'openai',attempt:n+1});const r=await request;if(!r.ok){if(retryable(r.status)&&n<1){await backoff(n);continue;}return {kind:'terminal_failure',errorCode:r.status===401?'AUTHENTICATION_FAILED':r.status===403?'AUTHORIZATION_FAILED':'SPECIALIST_EXECUTION_FAILED',errorMessage:'Specialist provider request failed'} as ExecResult<SoftwareOutput>;}const body:any=await responseJson(r),output=JSON.parse(responseText(body));if(!validSoftwareOutput(output))return {kind:'terminal_failure',errorCode:'SPECIALIST_OUTPUT_INVALID',errorMessage:'Specialist output schema validation failed'};return {kind:'success',output,externalExecutionId:body.id};}catch{if(n<1){await backoff(n);continue;}return {kind:'retryable_failure',errorCode:'SPECIALIST_EXECUTION_FAILED',errorMessage:'Specialist provider unavailable'} as ExecResult<SoftwareOutput>;}}return {kind:'terminal_failure',errorCode:'SPECIALIST_EXECUTION_FAILED',errorMessage:'Specialist provider unavailable'} as ExecResult<SoftwareOutput>;}
}
export class OpenAIValidationExecutor implements ValidationExecutor{
  constructor(private apiKey:string,private model=process.env.OPENAI_MODEL??'gpt-4.1-mini',private fetchImpl:FetchLike=fetch){}
  async execute(i:Parameters<ValidationExecutor['execute']>[0]){assertAuthorizedExecution(i.trustedContext);try{assertAuthorizedExecution(i.trustedContext);const request=this.fetchImpl('https://api.openai.com/v1/responses',{method:'POST',headers:{authorization:`Bearer ${this.apiKey}`,'content-type':'application/json'},signal:AbortSignal.timeout(120000),body:JSON.stringify({model:this.model,input:[{role:'system',content:'Return JSON with verdict PASS, PASS_WITH_CHANGES, or FAIL and arrays blocking_findings, non_blocking_findings, remediation_requirements.'},{role:'user',content:JSON.stringify({original_requirements:i.originalRequirements,codex_prompt:i.codexPrompt,codex_result:i.codexResult,changed_files:i.changedFiles,test_results:i.testResults})}],text:{format:{type:'json_object'}}})});await i.onInitiation?.({provider:'openai',purpose:'validation'});const r=await request;if(!r.ok)return {kind:'terminal_failure',errorCode:r.status===401?'AUTHENTICATION_FAILED':r.status===403?'AUTHORIZATION_FAILED':'VALIDATION_FAILED',errorMessage:'Validation provider request failed'};const output=JSON.parse(responseText(await responseJson(r)));if(!validValidation(output))return {kind:'terminal_failure',errorCode:'VALIDATION_FAILED',errorMessage:'Validation output schema validation failed'};return {kind:'success',output,externalExecutionId:(output as any).id};}catch{return {kind:'retryable_failure',errorCode:'VALIDATION_FAILED',errorMessage:'Validation provider unavailable'};}}
}
export async function createIsolatedWorkspace(context:ExecutionContext,rootInput:string){assertAuthorizedExecution(context);const policy=context.resolvedRepository;if(!policy)throw new Error('REPOSITORY_NOT_ALLOWED');const root=await realpath(resolve(rootInput)).catch(async()=>{await mkdir(resolve(rootInput),{recursive:true});return realpath(resolve(rootInput));});const sourcePath=await realpath(resolve(policy.source));const temp=await mkdtemp(join(root,`${policy.repositoryId.replace(/[^a-zA-Z0-9_-]/g,'_')}-`));let target:string|undefined;try{target=await realpath(temp);if(relative(root,target).startsWith(`..${sep}`)||resolve(target)===resolve(root))throw new Error('REPOSITORY_NOT_ALLOWED');const args=['clone','--no-hardlinks'];if(policy.approvedRef)args.push('--branch',policy.approvedRef);args.push('--',sourcePath,target);assertAuthorizedExecution(context);const child=spawn('git',args,{stdio:'ignore',shell:false});await new Promise<void>((res,rej)=>{child.once('error',rej);child.once('exit',c=>c===0?res():rej(new Error('REPOSITORY_NOT_ALLOWED')))});return {path:target,cleanup:()=>rm(target!,{recursive:true,force:true})};}catch(error){await rm(target??temp,{recursive:true,force:true}).catch(()=>{});throw error;}}
export class ProcessCodexExecutor implements CodexExecutor{
  constructor(private command=process.env.CODEX_COMMAND??'codex',private root=process.env.WORKSPACE_ROOT??join(process.cwd(),'workspaces'),private spawnImpl:SpawnLike=spawn as unknown as SpawnLike,private workspaceFactory:(context:ExecutionContext,root:string)=>Promise<WorkspaceLike>=createIsolatedWorkspace,private timeoutMs=EXTERNAL_EXECUTION_TIMEOUT_MS){}
  async execute(i:Parameters<CodexExecutor['execute']>[0]){assertAuthorizedExecution(i.trustedContext);if(!i.trustedContext.resolvedRepository)return {kind:'terminal_failure',errorCode:'REPOSITORY_NOT_ALLOWED',errorMessage:'Repository is required'} as ExecResult<any>;let ws;try{ws=await this.workspaceFactory(i.trustedContext,this.root);}catch{return {kind:'terminal_failure',errorCode:'REPOSITORY_NOT_ALLOWED',errorMessage:'Repository workspace could not be prepared'} as ExecResult<any>;}try{assertAuthorizedExecution(i.trustedContext);const p=this.spawnImpl(this.command,['exec','--ephemeral','--json','--sandbox','workspace-write','--ask-for-approval','never','--cd',ws.path,'-'],{cwd:ws.path,env:{PATH:process.env.PATH??''},stdio:['pipe','pipe','pipe'],shell:false});i.onInitiation?.({pid:p.pid,workspace:ws.path});p.stdin.end(i.promptArtifact.implementation_instructions);const result=await captureProcess(p,this.timeoutMs);const output={changedFiles:[],testResults:[],resultSummary:result.out.slice(-4000),exitCode:result.code};return result.code===0?{kind:'success',output,externalExecutionId:randomUUID()}:{kind:'terminal_failure',errorCode:'CODEX_EXECUTION_FAILED',errorMessage:'Codex process failed',output};}catch{return {kind:'retryable_failure',errorCode:'CODEX_EXECUTION_FAILED',errorMessage:'Codex process could not be reconciled'};}finally{await ws.cleanup();}}
}
export class RootlessContainerCodexExecutor implements CodexExecutor{
  constructor(private image=process.env.CODEX_CONTAINER_IMAGE??'codex-runner:latest',private runtime=process.env.CONTAINER_RUNTIME??'docker',private root=process.env.WORKSPACE_ROOT??join(process.cwd(),'workspaces'),private spawnImpl:SpawnLike=spawn as unknown as SpawnLike,private workspaceFactory:(context:ExecutionContext,root:string)=>Promise<WorkspaceLike>=createIsolatedWorkspace,private platform=process.platform,private timeoutMs=EXTERNAL_EXECUTION_TIMEOUT_MS){}
  async execute(i:Parameters<CodexExecutor['execute']>[0]):Promise<ExecResult<any>>{assertAuthorizedExecution(i.trustedContext);if(this.platform!=='linux')return {kind:'terminal_failure',errorCode:'DEPENDENCY_UNAVAILABLE',errorMessage:'Rootless Linux container execution requires Linux'};if(!i.trustedContext.resolvedRepository)return {kind:'terminal_failure',errorCode:'REPOSITORY_NOT_ALLOWED',errorMessage:'Repository is required'};let ws;try{ws=await this.workspaceFactory(i.trustedContext,this.root);}catch{return {kind:'terminal_failure',errorCode:'REPOSITORY_NOT_ALLOWED',errorMessage:'Repository workspace could not be prepared'};}try{assertAuthorizedExecution(i.trustedContext);const spec=buildContainerSpec(this.runtime,this.image,ws.path,i.promptArtifact.implementation_instructions);const p=this.spawnImpl(spec.command,spec.args,{shell:spec.shell,stdio:['pipe','pipe','pipe'],env:spec.env});i.onInitiation?.({pid:p.pid,runtime:this.runtime,workspace:ws.path});p.stdin.end(i.promptArtifact.implementation_instructions);const result=await captureProcess(p,this.timeoutMs);const output={changedFiles:[],testResults:[],resultSummary:result.out.slice(-4000),exitCode:result.code};return result.code===0?{kind:'success',output,externalExecutionId:randomUUID()}:{kind:'terminal_failure',errorCode:'CODEX_EXECUTION_FAILED',errorMessage:'Container Codex process failed',output};}catch{return {kind:'retryable_failure',errorCode:'CODEX_EXECUTION_FAILED',errorMessage:'Container runtime unavailable'};}finally{await ws.cleanup();}}
}
export function buildContainerSpec(runtime:string,image:string,workspace:string,_prompt:string){return {command:runtime,args:['run','--rm','--user','1000:1000','--read-only','--network','none','--cap-drop','ALL','--security-opt','no-new-privileges','--pids-limit','128','--cpus','2','--memory','2g','--mount',`type=bind,src=${workspace},dst=/workspace,rw`,image,'codex','exec','--ephemeral','--json','--sandbox','workspace-write','--ask-for-approval','never','--cd','/workspace','-'],env:{PATH:process.env.PATH??''},shell:false as const};}
