import {Pool,PoolClient} from 'pg'; import {createHash,randomUUID} from 'node:crypto'; import {APPROVAL_STATUSES,ApprovalRequest,Artifact,Attempt,AttemptState,MATERIAL_APPROVAL_CATEGORIES,MaterialApprovalCategory,RoutingCandidate,RoutingClarification,RoutingDecision,Stage,StageType,Workflow,WorkflowStatus,assertTransition} from './domain.js'; import {resolveSpecialist} from './registry.js'; import {ApprovalStore,ClarificationStore,Event,OverrideStore,PersistenceStore,RequestIdempotency,RoutingHistoryStore,RoutingResolutionStore,StageClaim,hash} from './store.js';
export class PgStore implements PersistenceStore,RoutingHistoryStore,RoutingResolutionStore,ClarificationStore,ApprovalStore,OverrideStore {
 readonly pool:Pool;
 constructor(url=process.env.DATABASE_URL){if(!url)throw new Error('DATABASE_URL_REQUIRED');this.pool=new Pool({connectionString:url,max:10});}
 private async event(c:PoolClient,e:Omit<Event,'id'|'sequence'|'createdAt'>){const q=await c.query(`INSERT INTO workflow_events(id,workflow_id,sequence,event_type,actor_type,actor_id,stage_id,metadata) SELECT $1,$2,COALESCE(MAX(sequence),0)+1,$3,$4,$5,$6,$7 FROM workflow_events WHERE workflow_id=$2 RETURNING id,workflow_id AS "workflowId",sequence,event_type AS "eventType",actor_type AS "actorType",actor_id AS "actorId",stage_id AS "stageId",metadata,created_at AS "createdAt"`,[randomUUID(),e.workflowId,e.eventType,e.actorType,e.actorId,e.stageId??null,e.metadata??null]);return q.rows[0] as Event;}
 async createWorkflow(input:Omit<Workflow,'id'|'status'|'version'|'createdAt'|'updatedAt'>,callerId='anonymous',operation='create',key=input.requestId,requestHash=hash(input)){const c=await this.pool.connect();try{await c.query('BEGIN');const prior=await c.query('SELECT * FROM request_idempotency WHERE caller_id=$1 AND operation=$2 AND idempotency_key=$3 FOR UPDATE',[callerId,operation,key]);if(prior.rowCount){if(prior.rows[0].request_hash!==requestHash)throw new Error('IDEMPOTENCY_KEY_REUSED');const w=await c.query('SELECT * FROM workflows WHERE id=$1',[prior.rows[0].workflow_id]);await c.query('COMMIT');return this.row(w.rows[0]);}const id=randomUUID(),now=new Date();await c.query(`INSERT INTO workflows(id,request_id,workflow_type,logical_specialist_id,runtime_id,status,validation_required,failure_code,failure_message,objective,context,requires_implementation,created_at,updated_at,version) VALUES($1,$2,$3,$4,$5,'CREATED',$6,NULL,NULL,$7,$8,$9,$10,$10,0) ON CONFLICT(request_id) DO NOTHING`,[id,input.requestId,input.workflowType,input.logicalSpecialistId,input.runtimeId??null,input.validationRequired??null,input.objective,input.context,input.requiresImplementation,now]);const q=await c.query('SELECT * FROM workflows WHERE request_id=$1 FOR UPDATE',[input.requestId]);const w=this.row(q.rows[0]);if(w.status==='CREATED'&&w.logicalSpecialistId){await this.event(c,{workflowId:w.id,eventType:'WORKFLOW_ROUTED',actorType:'system',actorId:'router',metadata:{runtimeDisposition:'resolved'}});await c.query("UPDATE workflows SET status='ROUTED',version=1,updated_at=now() WHERE id=$1",[w.id]);w.status='ROUTED';w.version=1;}await c.query('INSERT INTO request_idempotency(caller_id,operation,idempotency_key,request_hash,workflow_id) VALUES($1,$2,$3,$4,$5) ON CONFLICT(caller_id,operation,idempotency_key) DO NOTHING',[callerId,operation,key,requestHash,w.id]);const mapped=await c.query('SELECT request_hash,workflow_id FROM request_idempotency WHERE caller_id=$1 AND operation=$2 AND idempotency_key=$3 FOR UPDATE',[callerId,operation,key]);if(mapped.rows[0].request_hash!==requestHash)throw new Error('IDEMPOTENCY_KEY_REUSED');await c.query('COMMIT');return w;}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
 async getWorkflow(id:string){const q=await this.pool.query('SELECT * FROM workflows WHERE id=$1',[id]);return q.rowCount?this.row(q.rows[0]):undefined;}
 async recordRoutingDecision(decision:RoutingDecision){const c=await this.pool.connect();try{await c.query('BEGIN');await this.insertRoutingDecision(c,decision);await c.query('COMMIT');return decision;}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
 async recordRoutingCandidates(candidates:RoutingCandidate[]){if(!candidates.length)return [];const c=await this.pool.connect();try{await c.query('BEGIN');for(const candidate of candidates)await this.insertRoutingCandidate(c,candidate);await c.query('COMMIT');return candidates;}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
 async recordRoutingDecisionWithCandidates(decision:RoutingDecision,candidates:RoutingCandidate[]){const c=await this.pool.connect();try{await c.query('BEGIN');await this.insertRoutingDecision(c,decision);for(const candidate of candidates){if(candidate.routingDecisionId!==decision.id)throw new Error('ROUTING_CANDIDATE_DECISION_MISMATCH');await this.insertRoutingCandidate(c,candidate);}await c.query('COMMIT');return {decision,candidates};}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
 async persistRoutingResolution(decision:RoutingDecision,candidates:RoutingCandidate[],clarificationQuestion?:string){
  const c=await this.pool.connect();
  try{
   await c.query('BEGIN');

   const wq=await c.query('SELECT * FROM workflows WHERE id=$1 FOR UPDATE',[decision.workflowId]);
   if(!wq.rowCount)throw new Error('WORKFLOW_NOT_FOUND');
   const workflow=this.row(wq.rows[0]);

   await this.insertRoutingDecision(c,decision);
   for(const candidate of candidates){
    if(candidate.routingDecisionId!==decision.id)throw new Error('ROUTING_CANDIDATE_DECISION_MISMATCH');
    await this.insertRoutingCandidate(c,candidate);
   }

   let clarification:RoutingClarification|undefined;
   let resultWorkflow:Workflow=workflow;

   if(decision.routingConfidence==='AMBIGUOUS'){
    if(!clarificationQuestion?.trim())throw new Error('CLARIFICATION_QUESTION_REQUIRED');
    assertTransition(workflow.status,'AWAITING_CLARIFICATION');

    clarification={
     id:randomUUID(),
     workflowId:decision.workflowId,
     routingDecisionId:decision.id,
     question:clarificationQuestion.trim(),
     status:'PENDING',
     response:null,
     createdAt:new Date().toISOString(),
     answeredAt:null
    };

    await c.query(
     'INSERT INTO routing_clarifications(id,workflow_id,routing_decision_id,question,status,response,created_at,answered_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8)',
     [clarification.id,clarification.workflowId,clarification.routingDecisionId,clarification.question,clarification.status,null,clarification.createdAt,null]
    );

    resultWorkflow=await this.updateWorkflowStatus(
     c,
     workflow,
     'AWAITING_CLARIFICATION',
     'system',
     'routing-clarification',
     {clarificationId:clarification.id,routingDecisionId:decision.id}
    );
   }else if(workflow.status==='CREATED'&&decision.routingConfidence!=='NO_MATCH'){
    if(!decision.selectedSpecialistId)throw new Error('ROUTING_SPECIALIST_REQUIRED');

    const target=resolveSpecialist(decision.selectedSpecialistId);
    if(!target||target.status!=='ACTIVE')throw new Error('INVALID_ROUTING_TARGET');

    await c.query(
     'UPDATE workflows SET logical_specialist_id=$2,runtime_id=$3,updated_at=now() WHERE id=$1',
     [workflow.id,target.specialistId,target.runtime?.runtimeId??null]
    );

    const projected:Workflow={
     ...workflow,
     logicalSpecialistId:target.specialistId,
     runtimeId:target.runtime?.runtimeId??undefined,
     updatedAt:new Date().toISOString()
    };

    resultWorkflow=await this.updateWorkflowStatus(
     c,
     projected,
     'ROUTED',
     'system',
     'router',
     {routingDecisionId:decision.id,routingConfidence:decision.routingConfidence}
    );
   }

   await c.query('COMMIT');
   return {decision,candidates,clarification,workflow:resultWorkflow};
  }catch(e){
   await c.query('ROLLBACK');
   throw e;
  }finally{
   c.release();
  }
 }
 async getRoutingDecision(id:string){const q=await this.pool.query('SELECT id,workflow_id AS "workflowId",selected_specialist_id AS "selectedSpecialistId",routing_confidence AS "routingConfidence",routing_reason AS "routingReason",decision_type AS "decisionType",supersedes_decision_id AS "supersedesDecisionId",created_at AS "createdAt" FROM routing_decisions WHERE id=$1',[id]);return q.rowCount?this.routingDecisionRow(q.rows[0]):undefined;}
 async getRoutingCandidates(decisionId:string){const q=await this.pool.query('SELECT id,routing_decision_id AS "routingDecisionId",specialist_id AS "specialistId",rank,match_reason AS "matchReason" FROM routing_candidates WHERE routing_decision_id=$1 ORDER BY rank,id',[decisionId]);return q.rows.map(row=>this.routingCandidateRow(row));}
 async getRoutingHistory(workflowId:string){const q=await this.pool.query('SELECT id,workflow_id AS "workflowId",selected_specialist_id AS "selectedSpecialistId",routing_confidence AS "routingConfidence",routing_reason AS "routingReason",decision_type AS "decisionType",supersedes_decision_id AS "supersedesDecisionId",created_at AS "createdAt" FROM routing_decisions WHERE workflow_id=$1 ORDER BY created_at,id',[workflowId]);return q.rows.map(row=>this.routingDecisionRow(row));}
 async getLatestRoutingDecision(workflowId:string){const q=await this.pool.query('SELECT id,workflow_id AS "workflowId",selected_specialist_id AS "selectedSpecialistId",routing_confidence AS "routingConfidence",routing_reason AS "routingReason",decision_type AS "decisionType",supersedes_decision_id AS "supersedesDecisionId",created_at AS "createdAt" FROM routing_decisions d WHERE workflow_id=$1 AND NOT EXISTS (SELECT 1 FROM routing_decisions newer WHERE newer.supersedes_decision_id=d.id) ORDER BY created_at DESC,id DESC LIMIT 1',[workflowId]);return q.rowCount?this.routingDecisionRow(q.rows[0]):undefined;}
 async applyUserOverride(workflowId:string,targetSpecialistId:string,reason='',actorId='user',expectedDecisionId?:string){
  const target=resolveSpecialist(targetSpecialistId);
  if(!target||target.status!=='ACTIVE')throw new Error('INVALID_OVERRIDE_TARGET');
  if(typeof reason!=='string'||reason.length>1000)throw new Error('INVALID_OVERRIDE_REASON');
  const c=await this.pool.connect();
  try {
   await c.query('BEGIN');
   const wq=await c.query('SELECT * FROM workflows WHERE id=$1 FOR UPDATE',[workflowId]);
   if(!wq.rowCount)throw new Error('WORKFLOW_NOT_FOUND');
   const workflow=this.row(wq.rows[0]);
   if(!['ROUTED','AWAITING_CLARIFICATION','AWAITING_APPROVAL'].includes(workflow.status))throw new Error('OVERRIDE_STATE_UNSAFE');
   const dq=await c.query('SELECT id,workflow_id AS "workflowId",selected_specialist_id AS "selectedSpecialistId",routing_confidence AS "routingConfidence",routing_reason AS "routingReason",decision_type AS "decisionType",supersedes_decision_id AS "supersedesDecisionId",created_at AS "createdAt" FROM routing_decisions d WHERE workflow_id=$1 AND NOT EXISTS (SELECT 1 FROM routing_decisions newer WHERE newer.supersedes_decision_id=d.id) ORDER BY created_at DESC,id DESC LIMIT 1',[workflowId]);
   if(!dq.rowCount)throw new Error('ROUTING_DECISION_NOT_FOUND');
   const previous=this.routingDecisionRow(dq.rows[0]);
   if(expectedDecisionId&&expectedDecisionId!==previous.id)throw new Error('STALE_ROUTING_DECISION');
   const priorCandidates=await c.query('SELECT specialist_id AS "specialistId",rank,match_reason AS "matchReason" FROM routing_candidates WHERE routing_decision_id=$1 ORDER BY rank,id',[previous.id]);
   if(previous.selectedSpecialistId===target.specialistId){
    await c.query('COMMIT');
    return {workflow,decision:previous,previousDecision:previous,candidates:priorCandidates.rows.map((r:any)=>({...r,id:randomUUID(),routingDecisionId:previous.id,rank:Number(r.rank)}))};
   }
   const decision:RoutingDecision={id:randomUUID(),workflowId,selectedSpecialistId:target.specialistId,routingConfidence:'PROBABLE',routingReason:`User override selected ${target.displayName} for the current task.${reason.trim()?` User reason: ${reason.trim()}`:''}`,decisionType:'USER_OVERRIDE',supersedesDecisionId:previous.id,createdAt:new Date().toISOString()};
   await this.insertRoutingDecision(c,decision);
   const candidates:RoutingCandidate[]=priorCandidates.rows.map((r:any)=>({id:randomUUID(),routingDecisionId:decision.id,specialistId:r.specialistId,rank:Number(r.rank),matchReason:r.matchReason}));
   for(const candidate of candidates)await this.insertRoutingCandidate(c,candidate);
   if(workflow.status==='AWAITING_CLARIFICATION'){
    const cq=await c.query("UPDATE routing_clarifications SET status='SUPERSEDED' WHERE workflow_id=$1 AND status='PENDING' RETURNING id",[workflowId]);
    if(!cq.rowCount)throw new Error('CLARIFICATION_NOT_FOUND');
   }
   await c.query('UPDATE workflows SET logical_specialist_id=$2,runtime_id=$3,updated_at=now() WHERE id=$1',[workflowId,target.specialistId,target.runtime?.runtimeId??null]);
   let updatedWorkflow:Workflow={...workflow,logicalSpecialistId:target.specialistId,runtimeId:target.runtime?.runtimeId??undefined,updatedAt:new Date().toISOString()};
   if(workflow.status==='AWAITING_CLARIFICATION')updatedWorkflow=await this.updateWorkflowStatus(c,{...workflow,logicalSpecialistId:target.specialistId,runtimeId:target.runtime?.runtimeId??undefined},'ROUTED','system','routing-override',{previousDecisionId:previous.id,decisionId:decision.id,clarificationResolution:'SUPERSEDED'});
   await this.event(c,{workflowId,eventType:'ROUTING_OVERRIDDEN',actorType:'principal',actorId,metadata:{previousDecisionId:previous.id,previousSpecialistId:previous.selectedSpecialistId,overrideDecisionId:decision.id,targetSpecialistId:target.specialistId,reason:reason.trim()||undefined}});
   await c.query('COMMIT');
   return {workflow:updatedWorkflow,decision,previousDecision:previous,candidates};
  } catch(e){await c.query('ROLLBACK');throw e;} finally{c.release();}
 }
 async createPendingApproval(input:Omit<ApprovalRequest,'id'|'status'|'decisionReason'|'decidedBy'|'createdAt'|'decidedAt'>){const c=await this.pool.connect();try{await c.query('BEGIN');const q=await c.query('SELECT * FROM workflows WHERE id=$1 FOR UPDATE',[input.workflowId]);if(!q.rowCount)throw new Error('WORKFLOW_NOT_FOUND');this.validateApprovalInput(input);const workflow=this.row(q.rows[0]);assertTransition(workflow.status,'AWAITING_APPROVAL');const approval={id:randomUUID(),...input,status:'PENDING' as const,decisionReason:null,decidedBy:null,createdAt:new Date().toISOString(),decidedAt:null};await c.query('INSERT INTO workflow_approvals(id,workflow_id,protected_action_id,scope_fingerprint,reason,categories,status,decision_reason,decided_by,created_at,decided_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)',[approval.id,approval.workflowId,approval.protectedActionId,approval.scopeFingerprint,approval.reason,approval.categories,approval.status,null,null,approval.createdAt,null]);await this.updateWorkflowStatus(c,workflow,'AWAITING_APPROVAL','system','approval-requested',{approvalId:approval.id,protectedActionId:approval.protectedActionId,categories:approval.categories});await c.query('COMMIT');return approval;}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
 async getApproval(id:string){const q=await this.pool.query(this.approvalSelect('WHERE id=$1'),[id]);return q.rowCount?this.approvalRow(q.rows[0]):undefined;}
 async getPendingApproval(workflowId:string,protectedActionId?:string){const clause=protectedActionId?'WHERE workflow_id=$1 AND protected_action_id=$2 AND status=\'PENDING\'':'WHERE workflow_id=$1 AND status=\'PENDING\'';const q=await this.pool.query(this.approvalSelect(clause),protectedActionId?[workflowId,protectedActionId]:[workflowId]);return q.rowCount?this.approvalRow(q.rows[0]):undefined;}
 async getApprovalHistory(workflowId:string){const q=await this.pool.query(this.approvalSelect('WHERE workflow_id=$1 ORDER BY created_at,id'),[workflowId]);return q.rows.map(row=>this.approvalRow(row));}
 async getApprovedApproval(workflowId:string,protectedActionId:string,scopeFingerprint?:string){const q=await this.pool.query(this.approvalSelect("WHERE workflow_id=$1 AND protected_action_id=$2 AND status='APPROVED' ORDER BY decided_at DESC,id DESC LIMIT 1"),[workflowId,protectedActionId]);if(!q.rowCount)return undefined;const approval=this.approvalRow(q.rows[0]);if(scopeFingerprint!==undefined&&approval.scopeFingerprint!==scopeFingerprint)throw new Error('APPROVAL_SCOPE_MISMATCH');return approval;}
 async decideApproval(id:string,status:'APPROVED'|'REJECTED',decisionReason='',decidedBy?:string){if(!(APPROVAL_STATUSES as readonly string[]).includes(status))throw new Error('INVALID_APPROVAL_STATUS');const c=await this.pool.connect();try{await c.query('BEGIN');const q=await c.query(this.approvalSelect('WHERE id=$1 FOR UPDATE'),[id]);if(!q.rowCount)throw new Error('APPROVAL_NOT_FOUND');const current=this.approvalRow(q.rows[0]);if(current.status!=='PENDING'){if(current.status===status)return current;throw new Error('APPROVAL_ALREADY_DECIDED');}const updated=await c.query(`UPDATE workflow_approvals SET status=$2,decision_reason=$3,decided_by=$4,decided_at=now() WHERE id=$1 AND status='PENDING' RETURNING id,workflow_id AS "workflowId",protected_action_id AS "protectedActionId",scope_fingerprint AS "scopeFingerprint",reason,categories,status,decision_reason AS "decisionReason",decided_by AS "decidedBy",created_at AS "createdAt",decided_at AS "decidedAt"`,[id,status,decisionReason?.trim()||null,decidedBy??null]);if(!updated.rowCount)throw new Error('APPROVAL_ALREADY_DECIDED');const approval=this.approvalRow(updated.rows[0]);const workflowQ=await c.query('SELECT * FROM workflows WHERE id=$1 FOR UPDATE',[approval.workflowId]);if(!workflowQ.rowCount)throw new Error('WORKFLOW_NOT_FOUND');const workflow=this.row(workflowQ.rows[0]);if(status==='APPROVED'){if(workflow.status!=='AWAITING_APPROVAL')throw new Error('APPROVAL_WORKFLOW_STATE_MISMATCH');await this.updateWorkflowStatus(c,workflow,'ROUTED','system','approval-approved',{approvalId:id});}else if(workflow.status==='AWAITING_APPROVAL')await this.updateWorkflowStatus(c,workflow,'FAILED','system','approval-rejected',{approvalId:id,reason:approval.decisionReason});await c.query('COMMIT');return approval;}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
 private validateApprovalInput(input:any){if(!input.protectedActionId?.trim()||!input.scopeFingerprint?.trim()||!input.reason?.trim())throw new Error('INVALID_APPROVAL_INPUT');if(!Array.isArray(input.categories)||!input.categories.length||new Set(input.categories).size!==input.categories.length||input.categories.some((x:string)=>!(MATERIAL_APPROVAL_CATEGORIES as readonly string[]).includes(x)))throw new Error('INVALID_APPROVAL_CATEGORY');}
 private approvalSelect(where:string){return `SELECT id,workflow_id AS "workflowId",protected_action_id AS "protectedActionId",scope_fingerprint AS "scopeFingerprint",reason,categories,status,decision_reason AS "decisionReason",decided_by AS "decidedBy",created_at AS "createdAt",decided_at AS "decidedAt" FROM workflow_approvals ${where}`;}
 private approvalRow(r:any):ApprovalRequest{return {...r,categories:[...r.categories] as MaterialApprovalCategory[],createdAt:new Date(r.createdAt).toISOString(),decidedAt:r.decidedAt?new Date(r.decidedAt).toISOString():null};}
 async createPendingClarification(input:Omit<RoutingClarification,'id'|'status'|'response'|'createdAt'|'answeredAt'>){const c=await this.pool.connect();try{await c.query('BEGIN');const wq=await c.query('SELECT * FROM workflows WHERE id=$1 FOR UPDATE',[input.workflowId]);if(!wq.rowCount)throw new Error('WORKFLOW_NOT_FOUND');const dq=await c.query('SELECT workflow_id,routing_confidence FROM routing_decisions WHERE id=$1 FOR SHARE',[input.routingDecisionId]);if(!dq.rowCount)throw new Error('ROUTING_DECISION_NOT_FOUND');if(dq.rows[0].workflow_id!==input.workflowId)throw new Error('CLARIFICATION_WORKFLOW_MISMATCH');if(dq.rows[0].routing_confidence!=='AMBIGUOUS')throw new Error('CLARIFICATION_REQUIRES_AMBIGUOUS_DECISION');const workflow=this.row(wq.rows[0]);assertTransition(workflow.status,'AWAITING_CLARIFICATION');const clarification={id:randomUUID(),workflowId:input.workflowId,routingDecisionId:input.routingDecisionId,question:input.question,status:'PENDING' as const,response:null,createdAt:new Date().toISOString(),answeredAt:null};await c.query('INSERT INTO routing_clarifications(id,workflow_id,routing_decision_id,question,status,response,created_at,answered_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8)',[clarification.id,clarification.workflowId,clarification.routingDecisionId,clarification.question,clarification.status,null,clarification.createdAt,null]);await this.updateWorkflowStatus(c,workflow,'AWAITING_CLARIFICATION','system','routing-clarification',{clarificationId:clarification.id,routingDecisionId:clarification.routingDecisionId});await c.query('COMMIT');return clarification;}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
 async getClarification(id:string){const q=await this.pool.query(this.clarificationSelect('WHERE id=$1'),[id]);return q.rowCount?this.clarificationRow(q.rows[0]):undefined;}
 async getPendingClarification(workflowId:string){const q=await this.pool.query(this.clarificationSelect("WHERE workflow_id=$1 AND status='PENDING'"),[workflowId]);return q.rowCount?this.clarificationRow(q.rows[0]):undefined;}
 async getClarificationHistory(workflowId:string){const q=await this.pool.query(this.clarificationSelect('WHERE workflow_id=$1 ORDER BY created_at,id'),[workflowId]);return q.rows.map(row=>this.clarificationRow(row));}
 async recordClarificationResponse(id:string,response:string){if(typeof response!=='string'||!response.trim())throw new Error('INVALID_CLARIFICATION_RESPONSE');const c=await this.pool.connect();try{await c.query('BEGIN');const q=await c.query(this.clarificationSelect('WHERE id=$1 FOR UPDATE'),[id]);if(!q.rowCount)throw new Error('CLARIFICATION_NOT_FOUND');if(q.rows[0].status!=='PENDING')throw new Error('CLARIFICATION_ALREADY_ANSWERED');const updated=await c.query(`UPDATE routing_clarifications SET status='ANSWERED',response=$2,answered_at=now() WHERE id=$1 AND status='PENDING' RETURNING id,workflow_id AS "workflowId",routing_decision_id AS "routingDecisionId",question,status,response,created_at AS "createdAt",answered_at AS "answeredAt"`,[id,response.trim()]);if(!updated.rowCount)throw new Error('CLARIFICATION_ALREADY_ANSWERED');await c.query('COMMIT');return this.clarificationRow(updated.rows[0]);}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
 async resumeClarification(workflowId:string,clarificationId:string,decision:RoutingDecision,candidates:RoutingCandidate[]){const c=await this.pool.connect();try{await c.query('BEGIN');const cq=await c.query(this.clarificationSelect('WHERE id=$1 AND workflow_id=$2 FOR UPDATE'),[clarificationId,workflowId]);if(!cq.rowCount)throw new Error('CLARIFICATION_NOT_FOUND');const clarification=this.clarificationRow(cq.rows[0]);if(clarification.status!=='ANSWERED')throw new Error('CLARIFICATION_RESPONSE_REQUIRED');const existing=await c.query('SELECT id,workflow_id AS "workflowId",selected_specialist_id AS "selectedSpecialistId",routing_confidence AS "routingConfidence",routing_reason AS "routingReason",decision_type AS "decisionType",supersedes_decision_id AS "supersedesDecisionId",created_at AS "createdAt" FROM routing_decisions WHERE supersedes_decision_id=$1 FOR SHARE',[clarification.routingDecisionId]);if(existing.rowCount){const d=this.routingDecisionRow(existing.rows[0]);await c.query('COMMIT');return {clarification,decision:d,candidates:await this.getRoutingCandidates(d.id),workflow:await this.getWorkflow(workflowId) as Workflow};}if(decision.workflowId!==workflowId||decision.decisionType!=='POST_CLARIFICATION'||decision.supersedesDecisionId!==clarification.routingDecisionId)throw new Error('INVALID_POST_CLARIFICATION_DECISION');await this.insertRoutingDecision(c,decision);for(const candidate of candidates){if(candidate.routingDecisionId!==decision.id)throw new Error('ROUTING_CANDIDATE_DECISION_MISMATCH');await this.insertRoutingCandidate(c,candidate);}const wq=await c.query('SELECT * FROM workflows WHERE id=$1 FOR UPDATE',[workflowId]);if(!wq.rowCount)throw new Error('WORKFLOW_NOT_FOUND');const workflow=this.row(wq.rows[0]);if(workflow.status!=='AWAITING_CLARIFICATION')throw new Error('CLARIFICATION_WORKFLOW_STATE_MISMATCH');const updated=await this.updateWorkflowStatus(c,workflow,'ROUTED','system','routing-resume',{clarificationId,decisionId:decision.id});await c.query('COMMIT');return {clarification,decision,candidates,workflow:updated};}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
 private clarificationSelect(where:string){return `SELECT id,workflow_id AS "workflowId",routing_decision_id AS "routingDecisionId",question,status,response,created_at AS "createdAt",answered_at AS "answeredAt" FROM routing_clarifications ${where}`;}
 private clarificationRow(r:any):RoutingClarification{return {...r,createdAt:new Date(r.createdAt).toISOString(),answeredAt:r.answeredAt?new Date(r.answeredAt).toISOString():null};}
 private async updateWorkflowStatus(c:PoolClient,workflow:Workflow,to:WorkflowStatus,actorType:string,actorId:string,metadata:unknown){assertTransition(workflow.status,to);const version=workflow.version+1;await c.query('UPDATE workflows SET status=$2,version=$3,updated_at=now() WHERE id=$1',[workflow.id,to,version]);await this.event(c,{workflowId:workflow.id,eventType:`WORKFLOW_${to}`,actorType,actorId,metadata});return {...workflow,status:to,version,updatedAt:new Date().toISOString()};}
 private async insertRoutingDecision(c:PoolClient,d:RoutingDecision){if(d.supersedesDecisionId){const q=await c.query('SELECT workflow_id FROM routing_decisions WHERE id=$1 FOR SHARE',[d.supersedesDecisionId]);if(!q.rowCount)throw new Error('SUPERSEDED_ROUTING_DECISION_NOT_FOUND');if(q.rows[0].workflow_id!==d.workflowId)throw new Error('SUPERSEDED_ROUTING_WORKFLOW_MISMATCH');}await c.query('INSERT INTO routing_decisions(id,workflow_id,selected_specialist_id,routing_confidence,routing_reason,decision_type,supersedes_decision_id,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8)',[d.id,d.workflowId,d.selectedSpecialistId,d.routingConfidence,d.routingReason,d.decisionType,d.supersedesDecisionId,d.createdAt]);}
 private async insertRoutingCandidate(c:PoolClient,candidate:RoutingCandidate){await c.query('INSERT INTO routing_candidates(id,routing_decision_id,specialist_id,rank,match_reason) VALUES($1,$2,$3,$4,$5)',[candidate.id,candidate.routingDecisionId,candidate.specialistId,candidate.rank,candidate.matchReason]);}
 async exclusive<T>(_id:string,fn:()=>Promise<T>){return fn();}
 async transitionWorkflow(w:Workflow,to:WorkflowStatus,actorType:string,actorId:string,metadata?:unknown,stageId?:string){const c=await this.pool.connect();try{await c.query('BEGIN');const q=await c.query('SELECT * FROM workflows WHERE id=$1 FOR UPDATE',[w.id]);if(!q.rowCount)throw new Error('WORKFLOW_NOT_FOUND');const current=this.row(q.rows[0]);assertTransition(current.status,to);await c.query('UPDATE workflows SET status=$2,version=$3,updated_at=now() WHERE id=$1',[w.id,to,current.version+1]);await this.event(c,{workflowId:w.id,eventType:`WORKFLOW_${to}`,actorType,actorId,stageId,metadata});await c.query('COMMIT');Object.assign(w,current,{status:to,version:current.version+1});return w;}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
 async claimStage(workflowId:string,key:string,stageType:StageType,runtimeId:string|undefined,ownerId:string):Promise<StageClaim>{const c=await this.pool.connect();try{await c.query('BEGIN');const wf=await c.query('SELECT id,status,logical_specialist_id FROM workflows WHERE id=$1 FOR UPDATE',[workflowId]);if(!wf.rowCount)throw new Error('WORKFLOW_NOT_FOUND');if(!wf.rows[0].logical_specialist_id)throw new Error('ROUTING_REQUIRED');if(wf.rows[0].status==='AWAITING_CLARIFICATION')throw new Error('CLARIFICATION_REQUIRED');if(wf.rows[0].status==='AWAITING_APPROVAL')throw new Error('APPROVAL_REQUIRED');const rejected=await c.query("SELECT id FROM workflow_approvals WHERE workflow_id=$1 AND protected_action_id=$2 AND status='REJECTED' LIMIT 1",[workflowId,key]);if(rejected.rowCount)throw new Error('APPROVAL_REJECTED');let q=await c.query('SELECT * FROM workflow_stages WHERE workflow_id=$1 AND logical_stage_key=$2 FOR UPDATE',[workflowId,key]);let stage:any=q.rows[0];if(!stage){stage={id:randomUUID(),workflow_id:workflowId,stage_type:stageType,logical_stage_key:key,attempt:0,status:'PENDING',runtime_id:runtimeId};await c.query('INSERT INTO workflow_stages(id,workflow_id,stage_type,logical_stage_key,runtime_id,status,attempt) VALUES($1,$2,$3,$4,$5,$6,$7)',[stage.id,workflowId,stageType,key,runtimeId??null,'PENDING',0]);}const latest=stage.status==='COMPLETE'?await c.query('SELECT * FROM workflow_attempts WHERE stage_id=$1 ORDER BY attempt_number DESC LIMIT 1 FOR UPDATE',[stage.id]):{rowCount:0,rows:[]};if(latest.rowCount){await c.query('COMMIT');return {stage:this.stageRow(stage),attempt:this.attemptRow(latest.rows[0]),existing:true};}const active=await c.query("SELECT * FROM workflow_attempts WHERE stage_id=$1 AND status IN ('CLAIMED','STARTING','RUNNING','STATUS_UNKNOWN') FOR UPDATE",[stage.id]);if(active.rowCount){await c.query('COMMIT');return {stage:this.stageRow(stage),attempt:this.attemptRow(active.rows[0]),existing:true};}const last=await c.query('SELECT COALESCE(MAX(attempt_number),0)+1 AS n FROM workflow_attempts WHERE stage_id=$1',[stage.id]);const attempt={id:randomUUID(),workflow_id:workflowId,stage_id:stage.id,logical_stage_key:key,attempt_number:Number(last.rows[0].n),owner_id:ownerId,status:'CLAIMED'};await c.query('INSERT INTO workflow_attempts(id,workflow_id,stage_id,logical_stage_key,attempt_number,owner_id,status) VALUES($1,$2,$3,$4,$5,$6,$7)',[attempt.id,workflowId,stage.id,key,attempt.attempt_number,ownerId,'CLAIMED']);await c.query('UPDATE workflow_stages SET attempt=$2 WHERE id=$1',[stage.id,attempt.attempt_number]);await this.event(c,{workflowId,eventType:'STAGE_CLAIMED',actorType:'worker',actorId:ownerId,stageId:stage.id,metadata:{attemptId:attempt.id,logicalStageKey:key}});await c.query('COMMIT');return {stage:this.stageRow({...stage,attempt:attempt.attempt_number}),attempt:this.attemptRow(attempt),existing:false};}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
 async recordInitiation(_workflowId:string,attemptId:string,evidence:unknown,ownerId?:string){const c=await this.pool.connect();try{await c.query('BEGIN');const q=await c.query("UPDATE workflow_attempts SET status='RUNNING',initiation_evidence=$2,updated_at=now() WHERE id=$1 AND ($3::text IS NULL OR owner_id=$3) AND status='CLAIMED' RETURNING *",[attemptId,evidence,ownerId??null]);if(!q.rowCount)throw new Error('ATTEMPT_NOT_OWNER');await c.query('COMMIT');return this.attemptRow(q.rows[0]);}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
 async completeStage(_workflowId:string,attemptId:string,externalExecutionId:string|undefined,artifactId:string|undefined,evidence:unknown,ownerId?:string){const c=await this.pool.connect();try{await c.query('BEGIN');const q=await c.query("UPDATE workflow_attempts SET status='SUCCEEDED',terminal_evidence=$2,updated_at=now() WHERE id=$1 AND ($3::text IS NULL OR owner_id=$3) AND status IN ('CLAIMED','RUNNING') RETURNING *",[attemptId,{evidence,externalExecutionId,artifactId},ownerId??null]);if(!q.rowCount)throw new Error('ATTEMPT_NOT_OWNER');await c.query("UPDATE workflow_stages SET status='COMPLETE',external_execution_id=$2,output_artifact_id=$3,completed_at=now() WHERE id=$1",[q.rows[0].stage_id,externalExecutionId??null,artifactId??null]);await c.query('COMMIT');return this.attemptRow(q.rows[0]);}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
 async failStage(_workflowId:string,attemptId:string,state:AttemptState,evidence?:unknown,ownerId?:string){const c=await this.pool.connect();try{await c.query('BEGIN');const q=await c.query('UPDATE workflow_attempts SET status=$2,terminal_evidence=$3,updated_at=now() WHERE id=$1 AND ($4::text IS NULL OR owner_id=$4) AND status IN (\'CLAIMED\',\'STARTING\',\'RUNNING\',\'STATUS_UNKNOWN\') RETURNING *',[attemptId,state,evidence??null,ownerId??null]);if(!q.rowCount)throw new Error('ATTEMPT_NOT_OWNER');await c.query("UPDATE workflow_stages SET status='FAILED' WHERE id=$1",[q.rows[0].stage_id]);await c.query('COMMIT');return this.attemptRow(q.rows[0]);}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
 async markStageStatusUnknown(w:string,id:string,e:unknown){return this.failStage(w,id,'STATUS_UNKNOWN',e);}
 async addArtifact(workflowId:string,type:string,content:unknown){const json=JSON.stringify(content),a={id:randomUUID(),workflowId,artifactType:type,contentType:'application/json',contentJson:content,contentHash:createHash('sha256').update(json).digest('hex')};await this.pool.query('INSERT INTO artifacts(id,workflow_id,artifact_type,content_type,content_json,content_hash) VALUES($1,$2,$3,$4,$5,$6)',[a.id,workflowId,type,a.contentType,content,a.contentHash]);return a;}
 async appendEvent(e:Omit<Event,'id'|'sequence'|'createdAt'>){const c=await this.pool.connect();try{await c.query('BEGIN');await c.query('SELECT id FROM workflows WHERE id=$1 FOR UPDATE',[e.workflowId]);const out=await this.event(c,e);await c.query('COMMIT');return out;}catch(err){await c.query('ROLLBACK');throw err;}finally{c.release();}}
 async getStages(id:string){const q=await this.pool.query('SELECT id,workflow_id AS "workflowId",stage_type AS "stageType",logical_stage_key AS "logicalStageKey",runtime_id AS "runtimeId",status,attempt,external_execution_id AS "externalExecutionId",output_artifact_id AS "outputArtifactId" FROM workflow_stages WHERE workflow_id=$1 ORDER BY attempt',[id]);return q.rows as Stage[];}
 async getAttempts(id:string){const q=await this.pool.query('SELECT id,workflow_id AS "workflowId",stage_id AS "stageId",logical_stage_key AS "logicalStageKey",attempt_number AS "attemptNumber",owner_id AS "ownerId",status AS state,initiation_evidence AS "initiationEvidence",terminal_evidence AS "terminalEvidence" FROM workflow_attempts WHERE workflow_id=$1 ORDER BY attempt_number',[id]);return q.rows as Attempt[];}
 async getArtifacts(id:string){const q=await this.pool.query('SELECT id,workflow_id AS "workflowId",artifact_type AS "artifactType",content_type AS "contentType",content_json AS "contentJson",content_hash AS "contentHash" FROM artifacts WHERE workflow_id=$1 ORDER BY created_at',[id]);return q.rows as Artifact[];}
 async getEvents(id:string){const q=await this.pool.query('SELECT id,workflow_id AS "workflowId",sequence,event_type AS "eventType",actor_type AS "actorType",actor_id AS "actorId",stage_id AS "stageId",metadata,created_at AS "createdAt" FROM workflow_events WHERE workflow_id=$1 ORDER BY sequence',[id]);return q.rows as Event[];}
 async getRequestIdempotency(callerId:string,operation:string,key:string){const q=await this.pool.query('SELECT caller_id AS "callerId",operation,idempotency_key AS key,request_hash AS "requestHash",workflow_id AS "workflowId",result_reference AS "resultReference" FROM request_idempotency WHERE caller_id=$1 AND operation=$2 AND idempotency_key=$3',[callerId,operation,key]);return q.rowCount?q.rows[0] as RequestIdempotency:undefined;}
 async reconstructWorkflow(id:string){return {workflow:await this.getWorkflow(id),stages:await this.getStages(id),attempts:await this.getAttempts(id),artifacts:await this.getArtifacts(id),events:await this.getEvents(id)};}
 private row(r:any):Workflow{return {id:r.id,requestId:r.request_id,workflowType:r.workflow_type,logicalSpecialistId:r.logical_specialist_id,runtimeId:r.runtime_id,status:r.status,validationRequired:r.validation_required,effectiveClassification:r.effective_classification??'PUBLIC',objective:r.objective??'',context:r.context??{},requiresImplementation:r.requires_implementation??false,failureCode:r.failure_code,failureMessage:r.failure_message,version:Number(r.version),createdAt:new Date(r.created_at).toISOString(),updatedAt:new Date(r.updated_at).toISOString()};}
 private routingDecisionRow(r:any):RoutingDecision{return {...r,createdAt:new Date(r.createdAt).toISOString()};}
 private routingCandidateRow(r:any):RoutingCandidate{return {...r,rank:Number(r.rank)};}
 private stageRow(r:any):Stage{return {id:r.id,workflowId:r.workflow_id,stageType:r.stage_type,logicalStageKey:r.logical_stage_key,runtimeId:r.runtime_id,status:r.status,attempt:Number(r.attempt),externalExecutionId:r.external_execution_id,outputArtifactId:r.output_artifact_id};}
 private attemptRow(r:any):Attempt{return {id:r.id,workflowId:r.workflow_id,stageId:r.stage_id,logicalStageKey:r.logical_stage_key,attemptNumber:Number(r.attempt_number),ownerId:r.owner_id,state:r.status,initiationEvidence:r.initiation_evidence,terminalEvidence:r.terminal_evidence};}
}
