import {Pool,PoolClient} from 'pg'; import {createHash,randomUUID} from 'node:crypto'; import {Artifact,Attempt,AttemptState,Stage,StageType,Workflow,WorkflowStatus,assertTransition} from './domain.js'; import {Event,PersistenceStore,RequestIdempotency,StageClaim,hash} from './store.js';
export class PgStore implements PersistenceStore {
 readonly pool:Pool;
 constructor(url=process.env.DATABASE_URL){if(!url)throw new Error('DATABASE_URL_REQUIRED');this.pool=new Pool({connectionString:url,max:10});}
 private async event(c:PoolClient,e:Omit<Event,'id'|'sequence'|'createdAt'>){const q=await c.query(`INSERT INTO workflow_events(id,workflow_id,sequence,event_type,actor_type,actor_id,stage_id,metadata) SELECT $1,$2,COALESCE(MAX(sequence),0)+1,$3,$4,$5,$6,$7 FROM workflow_events WHERE workflow_id=$2 RETURNING id,workflow_id AS "workflowId",sequence,event_type AS "eventType",actor_type AS "actorType",actor_id AS "actorId",stage_id AS "stageId",metadata,created_at AS "createdAt"`,[randomUUID(),e.workflowId,e.eventType,e.actorType,e.actorId,e.stageId??null,e.metadata??null]);return q.rows[0] as Event;}
 async createWorkflow(input:Omit<Workflow,'id'|'status'|'version'|'createdAt'|'updatedAt'>,callerId='anonymous',operation='create',key=input.requestId,requestHash=hash(input)){const c=await this.pool.connect();try{await c.query('BEGIN');const prior=await c.query('SELECT * FROM request_idempotency WHERE caller_id=$1 AND operation=$2 AND idempotency_key=$3 FOR UPDATE',[callerId,operation,key]);if(prior.rowCount){if(prior.rows[0].request_hash!==requestHash)throw new Error('IDEMPOTENCY_KEY_REUSED');const w=await c.query('SELECT * FROM workflows WHERE id=$1',[prior.rows[0].workflow_id]);await c.query('COMMIT');return this.row(w.rows[0]);}const id=randomUUID(),now=new Date();await c.query(`INSERT INTO workflows(id,request_id,workflow_type,logical_specialist_id,runtime_id,status,validation_required,failure_code,failure_message,objective,context,requires_implementation,created_at,updated_at,version) VALUES($1,$2,$3,$4,$5,'CREATED',$6,NULL,NULL,$7,$8,$9,$10,$10,0) ON CONFLICT(request_id) DO NOTHING`,[id,input.requestId,input.workflowType,input.logicalSpecialistId,input.runtimeId??null,input.validationRequired??null,input.objective,input.context,input.requiresImplementation,now]);const q=await c.query('SELECT * FROM workflows WHERE request_id=$1 FOR UPDATE',[input.requestId]);const w=this.row(q.rows[0]);if(w.status==='CREATED'){await this.event(c,{workflowId:w.id,eventType:'WORKFLOW_ROUTED',actorType:'system',actorId:'router',metadata:{runtimeDisposition:'resolved'}});await c.query("UPDATE workflows SET status='ROUTED',version=1,updated_at=now() WHERE id=$1",[w.id]);w.status='ROUTED';w.version=1;}await c.query('INSERT INTO request_idempotency(caller_id,operation,idempotency_key,request_hash,workflow_id) VALUES($1,$2,$3,$4,$5) ON CONFLICT(caller_id,operation,idempotency_key) DO NOTHING',[callerId,operation,key,requestHash,w.id]);const mapped=await c.query('SELECT request_hash,workflow_id FROM request_idempotency WHERE caller_id=$1 AND operation=$2 AND idempotency_key=$3 FOR UPDATE',[callerId,operation,key]);if(mapped.rows[0].request_hash!==requestHash)throw new Error('IDEMPOTENCY_KEY_REUSED');await c.query('COMMIT');return w;}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
 async getWorkflow(id:string){const q=await this.pool.query('SELECT * FROM workflows WHERE id=$1',[id]);return q.rowCount?this.row(q.rows[0]):undefined;}
 async exclusive<T>(_id:string,fn:()=>Promise<T>){return fn();}
 async transitionWorkflow(w:Workflow,to:WorkflowStatus,actorType:string,actorId:string,metadata?:unknown,stageId?:string){const c=await this.pool.connect();try{await c.query('BEGIN');const q=await c.query('SELECT * FROM workflows WHERE id=$1 FOR UPDATE',[w.id]);if(!q.rowCount)throw new Error('WORKFLOW_NOT_FOUND');const current=this.row(q.rows[0]);assertTransition(current.status,to);await c.query('UPDATE workflows SET status=$2,version=$3,updated_at=now() WHERE id=$1',[w.id,to,current.version+1]);await this.event(c,{workflowId:w.id,eventType:`WORKFLOW_${to}`,actorType,actorId,stageId,metadata});await c.query('COMMIT');Object.assign(w,current,{status:to,version:current.version+1});return w;}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
 async claimStage(workflowId:string,key:string,stageType:StageType,runtimeId:string|undefined,ownerId:string):Promise<StageClaim>{const c=await this.pool.connect();try{await c.query('BEGIN');const wf=await c.query('SELECT id FROM workflows WHERE id=$1 FOR UPDATE',[workflowId]);if(!wf.rowCount)throw new Error('WORKFLOW_NOT_FOUND');let q=await c.query('SELECT * FROM workflow_stages WHERE workflow_id=$1 AND logical_stage_key=$2 FOR UPDATE',[workflowId,key]);let stage:any=q.rows[0];if(!stage){stage={id:randomUUID(),workflow_id:workflowId,stage_type:stageType,logical_stage_key:key,attempt:0,status:'PENDING',runtime_id:runtimeId};await c.query('INSERT INTO workflow_stages(id,workflow_id,stage_type,logical_stage_key,runtime_id,status,attempt) VALUES($1,$2,$3,$4,$5,$6,$7)',[stage.id,workflowId,stageType,key,runtimeId??null,'PENDING',0]);}const latest=stage.status==='COMPLETE'?await c.query('SELECT * FROM workflow_attempts WHERE stage_id=$1 ORDER BY attempt_number DESC LIMIT 1 FOR UPDATE',[stage.id]):{rowCount:0,rows:[]};if(latest.rowCount){await c.query('COMMIT');return {stage:this.stageRow(stage),attempt:this.attemptRow(latest.rows[0]),existing:true};}const active=await c.query("SELECT * FROM workflow_attempts WHERE stage_id=$1 AND status IN ('CLAIMED','STARTING','RUNNING','STATUS_UNKNOWN') FOR UPDATE",[stage.id]);if(active.rowCount){await c.query('COMMIT');return {stage:this.stageRow(stage),attempt:this.attemptRow(active.rows[0]),existing:true};}const last=await c.query('SELECT COALESCE(MAX(attempt_number),0)+1 AS n FROM workflow_attempts WHERE stage_id=$1',[stage.id]);const attempt={id:randomUUID(),workflow_id:workflowId,stage_id:stage.id,logical_stage_key:key,attempt_number:Number(last.rows[0].n),owner_id:ownerId,status:'CLAIMED'};await c.query('INSERT INTO workflow_attempts(id,workflow_id,stage_id,logical_stage_key,attempt_number,owner_id,status) VALUES($1,$2,$3,$4,$5,$6,$7)',[attempt.id,workflowId,stage.id,key,attempt.attempt_number,ownerId,'CLAIMED']);await c.query('UPDATE workflow_stages SET attempt=$2 WHERE id=$1',[stage.id,attempt.attempt_number]);await this.event(c,{workflowId,eventType:'STAGE_CLAIMED',actorType:'worker',actorId:ownerId,stageId:stage.id,metadata:{attemptId:attempt.id,logicalStageKey:key}});await c.query('COMMIT');return {stage:this.stageRow({...stage,attempt:attempt.attempt_number}),attempt:this.attemptRow(attempt),existing:false};}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
 async recordInitiation(_workflowId:string,attemptId:string,evidence:unknown,ownerId?:string){const c=await this.pool.connect();try{await c.query('BEGIN');const q=await c.query("UPDATE workflow_attempts SET status='RUNNING',initiation_evidence=$2,updated_at=now() WHERE id=$1 AND ($3::text IS NULL OR owner_id=$3) AND status='CLAIMED' RETURNING *",[attemptId,evidence,ownerId??null]);if(!q.rowCount)throw new Error('ATTEMPT_NOT_OWNER');await c.query('COMMIT');return this.attemptRow(q.rows[0]);}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
 async completeStage(_workflowId:string,attemptId:string,externalExecutionId:string|undefined,artifactId:string|undefined,evidence:unknown,ownerId?:string){const c=await this.pool.connect();try{await c.query('BEGIN');const q=await c.query("UPDATE workflow_attempts SET status='SUCCEEDED',terminal_evidence=$2,updated_at=now() WHERE id=$1 AND ($3::text IS NULL OR owner_id=$3) AND status IN ('CLAIMED','RUNNING') RETURNING *",[attemptId,{evidence,externalExecutionId,artifactId},ownerId??null]);if(!q.rowCount)throw new Error('ATTEMPT_NOT_OWNER');await c.query("UPDATE workflow_stages SET status='COMPLETE',external_execution_id=$2,output_artifact_id=$3,completed_at=now() WHERE id=$1",[q.rows[0].stage_id,externalExecutionId??null,artifactId??null]);await c.query('COMMIT');return this.attemptRow(q.rows[0]);}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
 async failStage(_workflowId:string,attemptId:string,state:AttemptState,evidence?:unknown,ownerId?:string){const c=await this.pool.connect();try{await c.query('BEGIN');const q=await c.query('UPDATE workflow_attempts SET status=$2,terminal_evidence=$3,updated_at=now() WHERE id=$1 AND ($4::text IS NULL OR owner_id=$4) AND status IN (\'CLAIMED\',\'STARTING\',\'RUNNING\',\'STATUS_UNKNOWN\') RETURNING *',[attemptId,state,evidence??null,ownerId??null]);if(!q.rowCount)throw new Error('ATTEMPT_NOT_OWNER');await c.query("UPDATE workflow_stages SET status='FAILED' WHERE id=$1",[q.rows[0].stage_id]);await c.query('COMMIT');return this.attemptRow(q.rows[0]);}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
 async markStageStatusUnknown(w:string,id:string,e:unknown){return this.failStage(w,id,'STATUS_UNKNOWN',e);}
 async addArtifact(workflowId:string,type:string,content:unknown){const json=JSON.stringify(content),a={id:randomUUID(),workflowId,artifactType:type,contentType:'application/json',contentJson:content,contentHash:createHash('sha256').update(json).digest('hex')};await this.pool.query('INSERT INTO artifacts(id,workflow_id,artifact_type,content_type,content_json,content_hash) VALUES($1,$2,$3,$4,$5,$6)',[a.id,workflowId,type,a.contentType,content,a.contentHash]);return a;}
 async appendEvent(e:Omit<Event,'id'|'sequence'|'createdAt'>){const c=await this.pool.connect();try{await c.query('BEGIN');await c.query('SELECT id FROM workflows WHERE id=$1 FOR UPDATE',[e.workflowId]);const out=await this.event(c,e);await c.query('COMMIT');return out;}catch(err){await c.query('ROLLBACK');throw err;}finally{c.release();}}
 async getStages(id:string){const q=await this.pool.query('SELECT id,workflow_id AS "workflowId",stage_type AS "stageType",logical_stage_key AS "logicalStageKey",runtime_id AS "runtimeId",status,attempt,external_execution_id AS "externalExecutionId",output_artifact_id AS "outputArtifactId" FROM workflow_stages WHERE workflow_id=$1 ORDER BY attempt',[id]);return q.rows as Stage[];}
 async getAttempts(id:string){const q=await this.pool.query('SELECT id,workflow_id AS "workflowId",stage_id AS "stageId",logical_stage_key AS "logicalStageKey",attempt_number AS "attemptNumber",owner_id AS "ownerId",status AS state,initiation_evidence AS "initiationEvidence",terminal_evidence AS "terminalEvidence" FROM workflow_attempts WHERE workflow_id=$1 ORDER BY attempt_number',[id]);return q.rows as Attempt[];}
 async getArtifacts(id:string){const q=await this.pool.query('SELECT id,workflow_id AS "workflowId",artifact_type AS "artifactType",content_type AS "contentType",content_json AS "contentJson",content_hash AS "contentHash" FROM artifacts WHERE workflow_id=$1 ORDER BY created_at',[id]);return q.rows as Artifact[];}
 async getEvents(id:string){const q=await this.pool.query('SELECT id,workflow_id AS "workflowId",sequence,event_type AS "eventType",actor_type AS "actorType",actor_id AS "actorId",stage_id AS "stageId",metadata,created_at AS "createdAt" FROM workflow_events WHERE workflow_id=$1 ORDER BY sequence',[id]);return q.rows as Event[];}
 async getRequestIdempotency(callerId:string,operation:string,key:string){const q=await this.pool.query('SELECT caller_id AS "callerId",operation,idempotency_key AS key,request_hash AS "requestHash",workflow_id AS "workflowId",result_reference AS "resultReference" FROM request_idempotency WHERE caller_id=$1 AND operation=$2 AND idempotency_key=$3',[callerId,operation,key]);return q.rowCount?q.rows[0] as RequestIdempotency:undefined;}
 async reconstructWorkflow(id:string){return {workflow:await this.getWorkflow(id),stages:await this.getStages(id),attempts:await this.getAttempts(id),artifacts:await this.getArtifacts(id),events:await this.getEvents(id)};}
 private row(r:any):Workflow{return {id:r.id,requestId:r.request_id,workflowType:r.workflow_type,logicalSpecialistId:r.logical_specialist_id,runtimeId:r.runtime_id,status:r.status,validationRequired:r.validation_required,effectiveClassification:r.effective_classification??'PUBLIC',objective:r.objective??'',context:r.context??{},requiresImplementation:r.requires_implementation??false,failureCode:r.failure_code,failureMessage:r.failure_message,version:Number(r.version),createdAt:new Date(r.created_at).toISOString(),updatedAt:new Date(r.updated_at).toISOString()};}
 private stageRow(r:any):Stage{return {id:r.id,workflowId:r.workflow_id,stageType:r.stage_type,logicalStageKey:r.logical_stage_key,runtimeId:r.runtime_id,status:r.status,attempt:Number(r.attempt),externalExecutionId:r.external_execution_id,outputArtifactId:r.output_artifact_id};}
 private attemptRow(r:any):Attempt{return {id:r.id,workflowId:r.workflow_id,stageId:r.stage_id,logicalStageKey:r.logical_stage_key,attemptNumber:Number(r.attempt_number),ownerId:r.owner_id,state:r.status,initiationEvidence:r.initiation_evidence,terminalEvidence:r.terminal_evidence};}
}
