import { CandidateEvidence, RoutingConfidence, RoutingResolution, SelectedCandidate, Specialist, TaskInterpretation } from './domain.js';
import { isCanonicalRoutableSpecialist, registry as canonicalRegistry, resolveRoutableSpecialist } from './registry.js';
import { RoutingHistoryStore, RoutingResolutionStore } from './store.js';
import { randomUUID } from 'node:crypto';

export interface InterpretationProvider { interpretRequest(input:{request:string;workflowContext?:TaskInterpretation['workflowContext'];repositoryContext?:TaskInterpretation['repositoryContext']}):Promise<unknown>|unknown; }

const stopWords = new Set(['and','the','for','with','from','into','this','that','review','analysis','planning','engineering','project']);
const words=(value:string)=>new Set(value.toLowerCase().replace(/[^a-z0-9_/-]+/g,' ').split(/[\s/_-]+/).filter(x=>x.length>2&&!stopWords.has(x)));
const unique=(values:string[])=>[...new Set(values.filter(x=>typeof x==='string'&&x.trim()).map(x=>x.trim().toLowerCase()))];
const overlap=(a:string,b:string)=>{const left=words(a),right=words(b);return [...left].filter(x=>right.has(x));};
const keywordMap:[RegExp,string,string][]=[[/github|pull request|\bpr\b|repository|repo|\bci\b|pipeline/i,'repository engineering','repository analysis'],[/security|vulnerability|threat|privacy/i,'security review','security analysis'],[/architect(?:ure|ural)|design|system/i,'architecture','architecture review'],[/chatgpt project|project folder|folder structure|project structure/i,'project structure','folder structure'],[/(?:build|create|configure)[^.]{0,40}\bgpt\b|gpt construction|gpt configuration/i,'GPT construction','GPT construction'],[/codex prompt|prompt for codex/i,'Codex prompt preparation','Codex prompt preparation'],[/bug|debug|failure|error|broken|fix/i,'debugging','incident debugging'],[/document|readme|specification/i,'documentation','technical writing']];

export function validateTaskInterpretation(value:unknown):value is TaskInterpretation { const v=value as any; if(!v||typeof v!=='object'||typeof v.intent!=='string'||!v.intent.trim()||typeof v.requestedOutcome!=='string'||!v.requestedOutcome.trim()||typeof v.requiresCurrentInformation!=='boolean'||typeof v.requiresExecutableRuntime!=='boolean')throw new Error('INVALID_TASK_INTERPRETATION');for(const field of ['taskCategories','requiredCapabilities','excludedCapabilities','inputTypes','expectedOutputTypes'] as const)if(!Array.isArray(v[field])||v[field].some((x:any)=>typeof x!=='string'||!x.trim()))throw new Error('INVALID_TASK_INTERPRETATION');if(v.explicitSpecialistRequest!==undefined&&typeof v.explicitSpecialistRequest!=='string')throw new Error('INVALID_TASK_INTERPRETATION');return true; }

export class DeterministicRequestInterpreter implements InterpretationProvider { interpretRequest(input:{request:string;workflowContext?:TaskInterpretation['workflowContext'];repositoryContext?:TaskInterpretation['repositoryContext']}):TaskInterpretation { if(typeof input?.request!=='string'||!input.request.trim())throw new Error('EMPTY_REQUEST');const request=input.request.trim();const categories:string[]=[];const capabilities:string[]=[];for(const [pattern,category,capability] of keywordMap)if(pattern.test(request)){categories.push(category);capabilities.push(capability);}const explicit=/\b(?:route|assign|send)\s+(?:this\s+)?(?:to|through)\s+([a-z0-9_-]+)/i.exec(request)?.[1];const result:TaskInterpretation={intent:request,requestedOutcome:request,taskCategories:unique(categories),requiredCapabilities:unique(capabilities),excludedCapabilities:[],inputTypes:input.repositoryContext?.repositoryId?['repository']:[],expectedOutputTypes:[],workflowContext:input.workflowContext??{},repositoryContext:input.repositoryContext,requiresCurrentInformation:/latest|current|today|recent/i.test(request),requiresExecutableRuntime:/execute|run|deploy|apply|change|modify/i.test(request),...(explicit?{explicitSpecialistRequest:explicit}: {})};validateTaskInterpretation(result);return result;} }

export function validateProviderInterpretation(value:unknown):TaskInterpretation { if(!validateTaskInterpretation(value))throw new Error('INVALID_TASK_INTERPRETATION');return value; }

function relationship(s:Specialist,context:TaskInterpretation['workflowContext']):CandidateEvidence['workflowRelationship'] { if(!context.currentSpecialistId)return 'none';if(s.specialistId===context.currentSpecialistId)return 'current';if(s.downstreamSpecialists.includes(context.currentSpecialistId))return 'upstream';if(s.upstreamSpecialists.includes(context.currentSpecialistId))return 'downstream';return 'none'; }
function excluded(s:Specialist,i:TaskInterpretation){const corpus=[i.intent,...i.taskCategories,...i.requiredCapabilities,...i.excludedCapabilities].join(' ');return s.exclusions.some(x=>overlap(x,corpus).length>0);}

export function selectCandidates(interpretation:TaskInterpretation,inputRegistry:Record<string,Specialist>=canonicalRegistry):SelectedCandidate[] { validateTaskInterpretation(interpretation);const result:SelectedCandidate[]=[];for(const s of Object.values(inputRegistry)){if(s.status!=='ACTIVE'||s.routingApproved===false||s.role==='ORCHESTRATOR'||s.role==='UNKNOWN_PENDING_REVIEW'||excluded(s,interpretation))continue;const categoryCorpus=interpretation.taskCategories.join(' ');const ownershipMatches=unique(s.primaryOwnership.flatMap(x=>overlap(x,categoryCorpus)));const capabilityMatches=unique(interpretation.requiredCapabilities.flatMap(required=>s.capabilities.flatMap(capability=>overlap(required,capability))));const relation=relationship(s,interpretation.workflowContext);if(!ownershipMatches.length&&!capabilityMatches.length&&relation==='none')continue;const specificity=ownershipMatches.length*2+capabilityMatches.length;const evidence:CandidateEvidence={specialistId:s.specialistId,registryVersion:s.registryVersion,ownershipMatches,capabilityMatches,workflowRelationship:relation,exclusionResult:'eligible',specificity,runtimeStatus:s.runtimeStatus,matchReason:''};const reasonParts:string[]=[];if(ownershipMatches.length)reasonParts.push(`primary ownership matches ${ownershipMatches.join(', ')}`);if(capabilityMatches.length)reasonParts.push(`required capability matches ${capabilityMatches.join(', ')}`);if(relation!=='none')reasonParts.push(`${relation} workflow relationship`);evidence.matchReason=reasonParts.join('; ');result.push({specialistId:s.specialistId,rank:0,matchReason:evidence.matchReason,evidence});}result.sort((a,b)=>b.evidence.ownershipMatches.length-a.evidence.ownershipMatches.length||b.evidence.specificity-a.evidence.specificity||b.evidence.capabilityMatches.length-a.evidence.capabilityMatches.length||a.specialistId.localeCompare(b.specialistId));return result.map((x,n)=>({...x,rank:n+1})); }

export async function interpretAndSelect(provider:InterpretationProvider,input:{request:string;workflowContext?:TaskInterpretation['workflowContext'];repositoryContext?:TaskInterpretation['repositoryContext']},inputRegistry:Record<string,Specialist>=canonicalRegistry){const interpretation=validateProviderInterpretation(await provider.interpretRequest(input));return {interpretation,candidates:selectCandidates(interpretation,inputRegistry)};}

function policyReason(confidence:RoutingConfidence,candidates:SelectedCandidate[]){if(confidence==='NO_MATCH')return 'No active registered specialist owns or sufficiently matches the required task capabilities.';const top=candidates[0],second=candidates[1];if(confidence==='CLEAR')return `${top.specialistId} has the strongest explicit ownership match; competing candidates provide only weaker generic evidence.`;if(confidence==='PROBABLE')return `${top.specialistId} is the strongest current match, but meaningful competing evidence remains.`;return `Top candidates ${top.specialistId} and ${second.specialistId} have materially comparable evidence; ownership responsibility remains unresolved.`;}
export function resolveRouting(candidates:SelectedCandidate[]):RoutingResolution {if(!Array.isArray(candidates))throw new Error('INVALID_CANDIDATES');if(!candidates.length)return {routingConfidence:'NO_MATCH',selectedSpecialistId:null,routingReason:policyReason('NO_MATCH',[]),candidates:[],requiresClarification:false};const [top,second]=candidates;const topOwnership=top.evidence.ownershipMatches.length;const secondOwnership=second?.evidence.ownershipMatches.length??0;const gap=top.evidence.specificity-(second?.evidence.specificity??0);let routingConfidence:RoutingConfidence;if(!second)routingConfidence=topOwnership?'CLEAR':'PROBABLE';else if(topOwnership>0&&secondOwnership===0)routingConfidence='CLEAR';else if(topOwnership===secondOwnership&&gap===0)routingConfidence='AMBIGUOUS';else if(gap>=2||topOwnership>secondOwnership)routingConfidence='PROBABLE';else routingConfidence='AMBIGUOUS';const ambiguous=routingConfidence==='AMBIGUOUS';return {routingConfidence,selectedSpecialistId:ambiguous?null:top.specialistId,routingReason:policyReason(routingConfidence,candidates),candidates,requiresClarification:ambiguous,clarificationQuestion:ambiguous?`Should this task focus on ${top.specialistId} or ${second.specialistId}?`:undefined};}

export function routingDecision(workflowId:string,resolution:RoutingResolution,decisionType:'INITIAL'|'POST_CLARIFICATION'|'DOWNSTREAM_ROUTE'|'FALLBACK'='INITIAL',supersedesDecisionId:string|null=null){return {id:randomUUID(),workflowId,selectedSpecialistId:resolution.selectedSpecialistId,routingConfidence:resolution.routingConfidence,routingReason:resolution.routingReason,decisionType,supersedesDecisionId,createdAt:new Date().toISOString()};}
export function validateCanonicalRoutingResolution(resolution: RoutingResolution): void {
  if (!resolution || !Array.isArray(resolution.candidates)) throw new Error('INVALID_ROUTING_RESOLUTION');
  const ids = new Set<string>();
  for (const candidate of resolution.candidates) {
    const specialist = resolveRoutableSpecialist(candidate.specialistId);
    if (!specialist || !isCanonicalRoutableSpecialist(specialist)) throw new Error('INVALID_ROUTING_TARGET');
    if (candidate.evidence.specialistId !== candidate.specialistId || candidate.evidence.registryVersion !== specialist.registryVersion) {
      throw new Error('STALE_ROUTING_TARGET');
    }
    if (ids.has(candidate.specialistId)) throw new Error('DUPLICATE_ROUTING_TARGET');
    ids.add(candidate.specialistId);
  }
  if (resolution.selectedSpecialistId !== null) {
    const specialist = resolveRoutableSpecialist(resolution.selectedSpecialistId);
    if (!specialist || !ids.has(resolution.selectedSpecialistId)) throw new Error('INVALID_ROUTING_TARGET');
  }
  if ((resolution.routingConfidence === 'AMBIGUOUS' || resolution.routingConfidence === 'NO_MATCH') && resolution.selectedSpecialistId !== null) {
    throw new Error('INVALID_ROUTING_SELECTION');
  }
}

export async function persistResolvedRouting(store:RoutingHistoryStore&Partial<RoutingResolutionStore>,workflowId:string,resolution:RoutingResolution,decisionType:'INITIAL'|'POST_CLARIFICATION'|'DOWNSTREAM_ROUTE'|'FALLBACK'='INITIAL',supersedesDecisionId:string|null=null):Promise<any>{validateCanonicalRoutingResolution(resolution);const decision=routingDecision(workflowId,resolution,decisionType,supersedesDecisionId);const candidates=resolution.candidates.map(x=>({id:randomUUID(),routingDecisionId:decision.id,specialistId:x.specialistId,rank:x.rank,matchReason:x.matchReason}));if(store.persistRoutingResolution)return store.persistRoutingResolution(decision,candidates,resolution.clarificationQuestion);if(resolution.routingConfidence==='AMBIGUOUS')throw new Error('ROUTING_RESOLUTION_PERSISTENCE_UNAVAILABLE');return {...await store.recordRoutingDecisionWithCandidates(decision,candidates),workflow:undefined};}
